-- Kunjungan salesman In/Out. Jalankan SETELAH 003_pelanggan.sql
-- SQL Editor project yang sama dengan obos_baru, skema public.

CREATE TABLE IF NOT EXISTS public.kunjungan_sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES public.pelanggan (id_pelanggan),
  rute text NOT NULL,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  jarak double precision NOT NULL DEFAULT 0,
  CONSTRAINT kunjungan_sales_rute_chk CHECK (btrim(rute) <> ''),
  CONSTRAINT kunjungan_sales_jarak_chk CHECK (jarak >= 0)
);

COMMENT ON TABLE public.kunjungan_sales IS
  'Satu baris = satu toko, satu hari Jakarta. Jam dari HP salesman.';
COMMENT ON COLUMN public.kunjungan_sales.tanggal IS 'Hari kunjungan (Asia/Jakarta).';
COMMENT ON COLUMN public.kunjungan_sales.waktu_masuk IS 'Check-in resmi.';
COMMENT ON COLUMN public.kunjungan_sales.waktu_keluar IS 'Check-out resmi.';

CREATE UNIQUE INDEX IF NOT EXISTS kunjungan_sales_toko_hari_uidx
  ON public.kunjungan_sales (id_pelanggan, tanggal);
CREATE INDEX IF NOT EXISTS kunjungan_sales_rute_tanggal_idx
  ON public.kunjungan_sales (rute, tanggal DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.kunjungan_sales
  TO postgres, service_role;
GRANT SELECT ON TABLE public.kunjungan_sales TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.kunjungan_sales FROM authenticated;
REVOKE ALL ON TABLE public.kunjungan_sales FROM anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;

ALTER TABLE public.kunjungan_sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kunjungan_sales FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS kunjungan_sales_select ON public.kunjungan_sales;
CREATE POLICY kunjungan_sales_select
  ON public.kunjungan_sales
  FOR SELECT
  TO authenticated
  USING (
    public.rute_sales_saya() IS NOT NULL
    AND rute = public.rute_sales_saya()
  );

CREATE OR REPLACE FUNCTION public.sales_waktu_sekarang()
RETURNS timestamptz
LANGUAGE sql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT clock_timestamp();
$$;

DROP FUNCTION IF EXISTS public.sales_scan_kunjungan(text, boolean, double precision, double precision);
DROP FUNCTION IF EXISTS public.sales_scan_kunjungan(text, boolean, double precision, double precision, timestamptz);

CREATE OR REPLACE FUNCTION public.sales_scan_kunjungan(
  p_id_pelanggan text,
  p_keluar boolean,
  p_latitude double precision,
  p_longitude double precision,
  p_waktu timestamptz
)
RETURNS timestamptz
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_rute text;
  v_lat double precision;
  v_lng double precision;
  v_jarak double precision;
  v_tanggal date;
  v_id text;
  v_masuk timestamptz;
  v_keluar timestamptz;
  v_now timestamptz;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Tidak terautentikasi';
  END IF;
  IF NOT public.sales_sedang_login() THEN
    RAISE EXCEPTION 'Sesi tidak aktif';
  END IF;

  IF p_waktu IS NULL THEN
    RAISE EXCEPTION 'Waktu HP kosong';
  END IF;
  IF abs(extract(epoch FROM (p_waktu - clock_timestamp()))) > 180 THEN
    RAISE EXCEPTION 'Jam HP tidak sesuai waktu Jakarta. Nyalakan waktu otomatis, lalu scan lagi.';
  END IF;
  v_now := p_waktu;

  v_rute := public.rute_sales_saya();
  IF v_rute IS NULL THEN
    RAISE EXCEPTION 'Rute salesman kosong';
  END IF;

  v_id := btrim(COALESCE(p_id_pelanggan, ''));
  IF v_id = '' THEN
    RAISE EXCEPTION 'Toko kosong';
  END IF;
  IF p_latitude IS NULL OR p_longitude IS NULL THEN
    RAISE EXCEPTION 'Koordinat HP kosong';
  END IF;

  SELECT latitude, longitude
  INTO v_lat, v_lng
  FROM public.pelanggan
  WHERE id_pelanggan = v_id
    AND rute = v_rute
    AND COALESCE(aktif, true);

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Toko tidak ada di rute Anda';
  END IF;
  IF v_lat IS NULL OR v_lng IS NULL OR (v_lat = 0 AND v_lng = 0) THEN
    RAISE EXCEPTION 'Toko belum punya koordinat GPS.';
  END IF;

  v_jarak := 6371000 * 2 * asin(sqrt(least(1.0,
    power(sin(radians(p_latitude - v_lat) / 2), 2) +
    cos(radians(v_lat)) * cos(radians(p_latitude)) *
    power(sin(radians(p_longitude - v_lng) / 2), 2)
  )));

  IF v_jarak > 20 THEN
    RAISE EXCEPTION 'Anda masih % m dari toko. Mendekatlah, lalu scan lagi.',
      round(v_jarak);
  END IF;

  v_tanggal := (v_now AT TIME ZONE 'Asia/Jakarta')::date;

  SELECT waktu_masuk, waktu_keluar
  INTO v_masuk, v_keluar
  FROM public.kunjungan_sales
  WHERE id_pelanggan = v_id
    AND tanggal = v_tanggal;

  IF COALESCE(p_keluar, false) THEN
    IF v_masuk IS NULL THEN
      RAISE EXCEPTION 'Belum check-in hari ini. Scan masuk dulu.';
    END IF;
    IF v_keluar IS NOT NULL THEN
      RETURN v_keluar;
    END IF;
    UPDATE public.kunjungan_sales
    SET waktu_keluar = v_now,
        jarak = v_jarak
    WHERE id_pelanggan = v_id
      AND tanggal = v_tanggal;
    RETURN v_now;
  END IF;

  IF v_keluar IS NOT NULL THEN
    RAISE EXCEPTION 'Kunjungan toko ini hari ini sudah selesai.';
  END IF;
  IF v_masuk IS NOT NULL THEN
    RETURN v_masuk;
  END IF;

  INSERT INTO public.kunjungan_sales (
    id_pelanggan, rute, tanggal, waktu_masuk, waktu_keluar, jarak
  ) VALUES (
    v_id, v_rute, v_tanggal, v_now, NULL, v_jarak
  )
  ON CONFLICT (id_pelanggan, tanggal) DO UPDATE
  SET waktu_masuk = COALESCE(public.kunjungan_sales.waktu_masuk, EXCLUDED.waktu_masuk),
      jarak = EXCLUDED.jarak
  WHERE public.kunjungan_sales.waktu_keluar IS NULL;

  RETURN v_now;
END;
$$;

REVOKE ALL ON FUNCTION public.sales_waktu_sekarang() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sales_scan_kunjungan(text, boolean, double precision, double precision, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.sales_waktu_sekarang() TO authenticated;
GRANT EXECUTE ON FUNCTION public.sales_scan_kunjungan(text, boolean, double precision, double precision, timestamptz) TO authenticated;

NOTIFY pgrst, 'reload schema';
