-- Nota. Jalankan SETELAH supabase/005_barang.sql. Skema public.
-- Jika tabel transaksi_items versi lama sudah ada, file ini menghapusnya dulu.

CREATE TABLE IF NOT EXISTS public.transaksi (
  id_transaksi text PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES public.pelanggan (id_pelanggan),
  nama_pelanggan text NOT NULL,
  rute text NOT NULL,
  status text NOT NULL DEFAULT 'diproses',
  waktu_order timestamptz NOT NULL DEFAULT timezone('utc', now()),
  waktu_packed timestamptz,
  waktu_actual timestamptz,
  pending boolean NOT NULL DEFAULT false,
  id_setoran_buku bigint,
  CONSTRAINT transaksi_id_chk CHECK (btrim(id_transaksi) <> ''),
  CONSTRAINT transaksi_nama_chk CHECK (btrim(nama_pelanggan) <> ''),
  CONSTRAINT transaksi_rute_chk CHECK (btrim(rute) <> ''),
  CONSTRAINT transaksi_status_chk CHECK (
    status IN ('diproses', 'dikirim', 'terkirim', 'batal')
  ),
  CONSTRAINT transaksi_pending_chk CHECK (
    NOT pending
    OR (status = 'dikirim' AND waktu_actual IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS transaksi_rute_order_idx
  ON public.transaksi (rute, waktu_order DESC);
CREATE INDEX IF NOT EXISTS transaksi_pelanggan_idx
  ON public.transaksi (id_pelanggan);
CREATE INDEX IF NOT EXISTS transaksi_setoran_buku_idx
  ON public.transaksi (id_setoran_buku);

DROP TABLE IF EXISTS public.transaksi_items CASCADE;

CREATE TABLE public.transaksi_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_transaksi text NOT NULL REFERENCES public.transaksi (id_transaksi) ON DELETE CASCADE,
  id_barang text NOT NULL REFERENCES public.barang (id_barang),
  id_grup text,
  nama_barang text NOT NULL,
  harga_beli integer NOT NULL,
  harga_jual integer NOT NULL,
  qty_order integer NOT NULL,
  harga_jual_order integer NOT NULL,
  subtotal_jual_order integer GENERATED ALWAYS AS (qty_order * harga_jual_order) STORED,
  subtotal_beli_order integer GENERATED ALWAYS AS (qty_order * harga_beli) STORED,
  qty_packed integer,
  harga_jual_packed integer,
  subtotal_jual_packed integer GENERATED ALWAYS AS (qty_packed * harga_jual_packed) STORED,
  subtotal_beli_packed integer GENERATED ALWAYS AS (qty_packed * harga_beli) STORED,
  qty_actual integer,
  harga_jual_actual integer,
  subtotal_jual_actual integer GENERATED ALWAYS AS (qty_actual * harga_jual_actual) STORED,
  subtotal_beli_actual integer GENERATED ALWAYS AS (qty_actual * harga_beli) STORED,
  min_strat_1 integer NOT NULL DEFAULT 0,
  jual_strat_1 integer NOT NULL DEFAULT 0,
  min_strat_2 integer NOT NULL DEFAULT 0,
  jual_strat_2 integer NOT NULL DEFAULT 0,
  min_strat_3 integer NOT NULL DEFAULT 0,
  jual_strat_3 integer NOT NULL DEFAULT 0,
  min_strat_4 integer NOT NULL DEFAULT 0,
  jual_strat_4 integer NOT NULL DEFAULT 0,
  min_strat_5 integer NOT NULL DEFAULT 0,
  jual_strat_5 integer NOT NULL DEFAULT 0,
  CONSTRAINT transaksi_items_nama_chk CHECK (btrim(nama_barang) <> ''),
  CONSTRAINT transaksi_items_harga_beli_chk CHECK (harga_beli >= 0),
  CONSTRAINT transaksi_items_harga_jual_chk CHECK (harga_jual >= 0),
  CONSTRAINT transaksi_items_order_chk CHECK (
    qty_order >= 0 AND harga_jual_order >= 0
  ),
  CONSTRAINT transaksi_items_packed_chk CHECK (
    qty_packed IS NULL
    OR (qty_packed >= 0 AND harga_jual_packed IS NOT NULL AND harga_jual_packed >= 0)
  ),
  CONSTRAINT transaksi_items_actual_chk CHECK (
    qty_actual IS NULL
    OR (qty_actual >= 0 AND harga_jual_actual IS NOT NULL AND harga_jual_actual >= 0)
  ),
  CONSTRAINT transaksi_items_sku UNIQUE (id_transaksi, id_barang)
);

COMMENT ON TABLE public.transaksi_items IS
  'Baris nota. Harga beli, jual, dan strata dikunci saat salesman simpan. Strata dihitung dari qty grup (id_grup).';
COMMENT ON COLUMN public.transaksi_items.harga_beli IS 'Modal terkunci dari barang saat simpan.';
COMMENT ON COLUMN public.transaksi_items.harga_jual IS 'Harga jual katalog terkunci saat salesman simpan. Dasar strata; order/packed/actual hasil hitung.';
COMMENT ON COLUMN public.transaksi_items.id_grup IS 'Grup strata. Kosong = strata per SKU.';

CREATE INDEX IF NOT EXISTS transaksi_items_transaksi_idx
  ON public.transaksi_items (id_transaksi);
CREATE INDEX IF NOT EXISTS transaksi_items_grup_idx
  ON public.transaksi_items (id_transaksi, id_grup);

COMMENT ON COLUMN public.transaksi.id_setoran_buku IS
  'Buku setoran yang terbuka saat packing. FK ke setoran_buku menyusul. Kosong sampai buku ada.';

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.transaksi
  TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.transaksi_items
  TO postgres, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;
REVOKE ALL ON TABLE public.transaksi FROM anon;
REVOKE ALL ON TABLE public.transaksi_items FROM anon;
