-- Absensi gudang (orang). Jalankan SETELAH 001_login.sql. Skema public.

CREATE TABLE IF NOT EXISTS public.lokasi_gudang (
  id text PRIMARY KEY,
  nama text NOT NULL,
  latitude double precision,
  longitude double precision,
  CONSTRAINT lokasi_gudang_id_chk CHECK (btrim(id) <> ''),
  CONSTRAINT lokasi_gudang_nama_chk CHECK (btrim(nama) <> '')
);

COMMENT ON TABLE public.lokasi_gudang IS
  'Titik absensi. Scan masuk/keluar hanya dalam 20 meter.';

INSERT INTO public.lokasi_gudang (id, nama, latitude, longitude)
VALUES ('utama', 'Gudang Utama', NULL, NULL)
ON CONFLICT (id) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.lokasi_gudang
  TO postgres, service_role;
REVOKE ALL ON TABLE public.lokasi_gudang FROM anon, authenticated;

ALTER TABLE public.lokasi_gudang ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lokasi_gudang FORCE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.absensi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL REFERENCES public.users (email),
  peran text NOT NULL,
  rute text,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  id_setoran_buku bigint,
  CONSTRAINT absensi_peran_chk CHECK (peran IN ('gudang', 'pengirim', 'admin')),
  CONSTRAINT absensi_waktu_chk CHECK (
    waktu_keluar IS NULL
    OR (waktu_masuk IS NOT NULL AND waktu_keluar >= waktu_masuk)
  )
);

COMMENT ON TABLE public.absensi IS
  'Kehadiran orang. Satu email hanya satu sesi terbuka (waktu_keluar kosong).';
COMMENT ON COLUMN public.absensi.id_setoran_buku IS
  'Buku setoran yang terbuka saat scan masuk. FK ke setoran_buku menyusul. Kosong sampai buku ada.';

CREATE UNIQUE INDEX IF NOT EXISTS absensi_sesi_terbuka_uidx
  ON public.absensi (lower(email))
  WHERE waktu_keluar IS NULL;
CREATE INDEX IF NOT EXISTS absensi_tanggal_idx
  ON public.absensi (tanggal DESC, peran);
CREATE INDEX IF NOT EXISTS absensi_setoran_buku_idx
  ON public.absensi (id_setoran_buku);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.absensi
  TO postgres, service_role;
GRANT SELECT ON TABLE public.absensi TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;
REVOKE ALL ON TABLE public.absensi FROM anon;

ALTER TABLE public.absensi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.absensi FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS absensi_select_sendiri ON public.absensi;
CREATE POLICY absensi_select_sendiri
  ON public.absensi
  FOR SELECT
  TO authenticated
  USING (
    lower(btrim(email)) = lower(btrim(COALESCE(auth.jwt() ->> 'email', '')))
  );

CREATE OR REPLACE FUNCTION public.pastikan_di_gudang(
  p_latitude double precision,
  p_longitude double precision
)
RETURNS double precision
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_lat double precision;
  v_lng double precision;
  v_jarak double precision;
BEGIN
  IF p_latitude IS NULL OR p_longitude IS NULL THEN
    RAISE EXCEPTION 'Koordinat HP kosong';
  END IF;

  SELECT latitude, longitude
  INTO v_lat, v_lng
  FROM public.lokasi_gudang
  WHERE id = 'utama'
  LIMIT 1;

  IF NOT FOUND
     OR v_lat IS NULL OR v_lng IS NULL
     OR (v_lat = 0 AND v_lng = 0) THEN
    RAISE EXCEPTION 'Titik lokasi gudang belum diisi. Minta admin mengisi koordinat gudang, lalu scan lagi.';
  END IF;

  v_jarak := 6371000 * 2 * asin(sqrt(least(1.0,
    power(sin(radians(p_latitude - v_lat) / 2), 2) +
    cos(radians(v_lat)) * cos(radians(p_latitude)) *
    power(sin(radians(p_longitude - v_lng) / 2), 2)
  )));

  IF v_jarak > 20 THEN
    RAISE EXCEPTION 'Anda masih % m dari gudang. Mendekatlah, lalu scan lagi.',
      round(v_jarak);
  END IF;

  RETURN v_jarak;
END;
$$;

CREATE OR REPLACE FUNCTION public.gudang_id_absensi_saya()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT a.id
  FROM public.absensi a
  WHERE lower(btrim(a.email)) = lower(btrim(COALESCE(auth.jwt() ->> 'email', '')))
    AND a.peran IN ('gudang', 'admin')
    AND a.waktu_masuk IS NOT NULL
    AND a.waktu_keluar IS NULL
  ORDER BY a.waktu_masuk DESC, a.id DESC
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.gudang_status_lantai()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
  v_masuk timestamptz;
BEGIN
  IF NOT public.gudang_sedang_login() THEN
    RETURN jsonb_build_object(
      'login', false,
      'absensi_terbuka', false,
      'id_absensi', NULL,
      'waktu_masuk', NULL
    );
  END IF;

  SELECT a.id, a.waktu_masuk
  INTO v_id, v_masuk
  FROM public.absensi a
  WHERE lower(btrim(a.email)) = lower(btrim(COALESCE(auth.jwt() ->> 'email', '')))
    AND a.peran IN ('gudang', 'admin')
    AND a.waktu_masuk IS NOT NULL
    AND a.waktu_keluar IS NULL
  ORDER BY a.waktu_masuk DESC, a.id DESC
  LIMIT 1;

  RETURN jsonb_build_object(
    'login', true,
    'absensi_terbuka', v_id IS NOT NULL,
    'id_absensi', v_id,
    'waktu_masuk', v_masuk
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gudang_waktu_sekarang()
RETURNS timestamptz
LANGUAGE sql
VOLATILE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT clock_timestamp();
$$;

CREATE OR REPLACE FUNCTION public.gudang_lokasi_utama()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_nama text;
  v_lat double precision;
  v_lng double precision;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Tidak terautentikasi';
  END IF;

  SELECT l.nama, l.latitude, l.longitude
  INTO v_nama, v_lat, v_lng
  FROM public.lokasi_gudang l
  WHERE l.id = 'utama'
  LIMIT 1;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Lokasi gudang belum diisi.';
  END IF;

  RETURN jsonb_build_object(
    'nama', v_nama,
    'latitude', v_lat,
    'longitude', v_lng
  );
END;
$$;

DROP FUNCTION IF EXISTS public.gudang_scan_absensi(boolean, double precision, double precision);
DROP FUNCTION IF EXISTS public.gudang_scan_absensi(boolean, double precision, double precision, timestamptz);

CREATE OR REPLACE FUNCTION public.gudang_scan_absensi(
  p_keluar boolean,
  p_latitude double precision,
  p_longitude double precision,
  p_waktu timestamptz
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_email text;
  v_peran text;
  v_rute text;
  v_now timestamptz;
  v_tanggal date;
  v_id bigint;
BEGIN
  IF NOT public.gudang_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;

  IF p_waktu IS NULL THEN
    RAISE EXCEPTION 'Waktu HP kosong';
  END IF;
  IF abs(extract(epoch FROM (p_waktu - clock_timestamp()))) > 180 THEN
    RAISE EXCEPTION 'Jam HP tidak sesuai waktu Jakarta. Nyalakan waktu otomatis, lalu scan lagi.';
  END IF;
  v_now := p_waktu;
  v_tanggal := (timezone('Asia/Jakarta', v_now))::date;

  PERFORM public.pastikan_di_gudang(p_latitude, p_longitude);

  v_email := lower(btrim(COALESCE(auth.jwt() ->> 'email', '')));
  IF v_email = '' THEN
    RAISE EXCEPTION 'Email sesi kosong.';
  END IF;

  SELECT lower(btrim(u.peran)), u.rute INTO v_peran, v_rute
  FROM public.users u
  WHERE lower(btrim(u.email)) = v_email
  LIMIT 1;

  IF v_peran IS NULL OR v_peran NOT IN ('gudang', 'admin') THEN
    RAISE EXCEPTION 'Hanya gudang atau admin yang boleh scan absensi di aplikasi ini.';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext(v_email));

  IF p_keluar THEN
    SELECT a.id INTO v_id
    FROM public.absensi a
    WHERE lower(btrim(a.email)) = v_email
      AND a.waktu_keluar IS NULL
    ORDER BY a.waktu_masuk DESC NULLS LAST, a.id DESC
    LIMIT 1
    FOR UPDATE;

    IF v_id IS NULL THEN
      RAISE EXCEPTION 'Belum scan masuk.';
    END IF;

    UPDATE public.absensi
    SET waktu_keluar = v_now
    WHERE id = v_id
      AND waktu_keluar IS NULL;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Sudah scan pulang.';
    END IF;

    RETURN jsonb_build_object(
      'id_absensi', v_id,
      'tanggal', v_tanggal,
      'waktu', v_now,
      'keluar', true
    );
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.absensi a
    WHERE lower(btrim(a.email)) = v_email
      AND a.waktu_keluar IS NULL
  ) THEN
    RAISE EXCEPTION 'Sudah scan masuk.';
  END IF;

  INSERT INTO public.absensi (
    email, peran, rute, tanggal, waktu_masuk, waktu_keluar
  ) VALUES (
    v_email, v_peran, v_rute, v_tanggal, v_now, NULL
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'id_absensi', v_id,
    'tanggal', v_tanggal,
    'waktu', v_now,
    'keluar', false
  );
END;
$$;

REVOKE ALL ON FUNCTION public.pastikan_di_gudang(double precision, double precision) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pastikan_di_gudang(double precision, double precision)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_id_absensi_saya() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_id_absensi_saya()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_status_lantai() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_status_lantai()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_waktu_sekarang() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_waktu_sekarang()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_lokasi_utama() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_lokasi_utama()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_scan_absensi(boolean, double precision, double precision, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_scan_absensi(boolean, double precision, double precision, timestamptz)
  TO authenticated, postgres, service_role;

NOTIFY pgrst, 'reload schema';
