-- Satu buku setoran. Absensi + packing + opname ikut buku terbuka.
-- Tutup hanya admin. Setelah tutup, scan/packing membuka buku baru.
-- Snapshot SKU saat buku dibuka. Cetak tidak membuat baris.
-- Jalankan SETELAH 013. Boleh diulang.

CREATE TABLE IF NOT EXISTS public.setoran_buku (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  waktu_buka timestamptz NOT NULL DEFAULT clock_timestamp(),
  waktu_tutup timestamptz,
  ditutup boolean NOT NULL DEFAULT false,
  CONSTRAINT setoran_buku_tutup_chk CHECK (
    NOT ditutup OR waktu_tutup IS NOT NULL
  )
);

COMMENT ON TABLE public.setoran_buku IS
  'Satu-satunya buku. Absensi, packing, dan stok_opname memakai id ini.
   Hanya satu buku terbuka. Ditutup dari app admin.';
COMMENT ON COLUMN public.setoran_buku.tanggal IS
  'Label Jakarta saat buku dibuka. Bukan identitas.';

CREATE UNIQUE INDEX IF NOT EXISTS setoran_buku_terbuka_uidx
  ON public.setoran_buku ((ditutup))
  WHERE NOT ditutup;
CREATE INDEX IF NOT EXISTS setoran_buku_tanggal_idx
  ON public.setoran_buku (tanggal DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.setoran_buku
  TO postgres, service_role;
GRANT SELECT ON TABLE public.setoran_buku TO authenticated;
REVOKE ALL ON TABLE public.setoran_buku FROM anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;

ALTER TABLE public.setoran_buku ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.setoran_buku FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS setoran_buku_select ON public.setoran_buku;
CREATE POLICY setoran_buku_select
  ON public.setoran_buku
  FOR SELECT
  TO authenticated
  USING (
    public.gudang_sedang_login()
    OR public.admin_sedang_login()
  );

CREATE TABLE IF NOT EXISTS public.stok_opname (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES public.setoran_buku (id),
  tanggal date NOT NULL,
  id_barang text NOT NULL REFERENCES public.barang (id_barang),
  nama_barang text NOT NULL,
  stok_awal numeric(14, 4) NOT NULL DEFAULT 0,
  qty_packed numeric(14, 4) NOT NULL DEFAULT 0,
  stok_hitung numeric(14, 4) GENERATED ALWAYS AS (stok_awal - qty_packed) STORED,
  stok_fisik numeric(14, 4),
  selisih numeric(14, 4) GENERATED ALWAYS AS (
    stok_fisik - (stok_awal - qty_packed)
  ) STORED,
  dicek_stok_oleh text,
  CONSTRAINT stok_opname_nama_chk CHECK (btrim(nama_barang) <> ''),
  CONSTRAINT stok_opname_angka_chk CHECK (
    stok_awal >= 0
    AND qty_packed >= 0
    AND (stok_fisik IS NULL OR stok_fisik >= 0)
  )
);

COMMENT ON TABLE public.stok_opname IS
  'Satu baris = satu SKU di satu buku setoran. Diisi saat buku dibuka.';
COMMENT ON COLUMN public.stok_opname.stok_awal IS
  'Snapshot saat buku dibuka. Barang masuk di tengah buku menggeser kolom ini (hitung ikut).';
COMMENT ON COLUMN public.stok_opname.qty_packed IS 'Qty packing ke buku ini.';
COMMENT ON COLUMN public.stok_opname.stok_hitung IS 'stok_awal - qty_packed.';
COMMENT ON COLUMN public.stok_opname.stok_fisik IS 'Hitung fisik gudang. Konfirmasi admin memakai nilai ini ke barang.stok.';
COMMENT ON COLUMN public.stok_opname.selisih IS 'stok_fisik - stok_hitung. Kosong jika belum fisik.';
COMMENT ON COLUMN public.stok_opname.dicek_stok_oleh IS
  'Nama petugas yang mengisi stok_fisik baris ini.';

CREATE UNIQUE INDEX IF NOT EXISTS stok_opname_buku_sku_uidx
  ON public.stok_opname (id_setoran_buku, id_barang);
CREATE INDEX IF NOT EXISTS stok_opname_tanggal_idx
  ON public.stok_opname (tanggal DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.stok_opname
  TO postgres, service_role;
GRANT SELECT ON TABLE public.stok_opname TO authenticated;
REVOKE ALL ON TABLE public.stok_opname FROM anon;

ALTER TABLE public.stok_opname ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stok_opname FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS stok_opname_select ON public.stok_opname;
CREATE POLICY stok_opname_select
  ON public.stok_opname
  FOR SELECT
  TO authenticated
  USING (
    public.gudang_sedang_login()
    OR public.admin_sedang_login()
  );

ALTER TABLE public.absensi
  DROP CONSTRAINT IF EXISTS absensi_setoran_buku_fk;
ALTER TABLE public.absensi
  ADD CONSTRAINT absensi_setoran_buku_fk
  FOREIGN KEY (id_setoran_buku) REFERENCES public.setoran_buku (id);

ALTER TABLE public.transaksi
  DROP CONSTRAINT IF EXISTS transaksi_setoran_buku_fk;
ALTER TABLE public.transaksi
  ADD CONSTRAINT transaksi_setoran_buku_fk
  FOREIGN KEY (id_setoran_buku) REFERENCES public.setoran_buku (id);

COMMENT ON COLUMN public.absensi.id_setoran_buku IS
  'Buku setoran saat scan masuk. Setelah buku ditutup, scan masuk berikutnya ke buku baru.';
COMMENT ON COLUMN public.transaksi.id_setoran_buku IS
  'Buku setoran saat packing pertama nota ini.';

CREATE OR REPLACE FUNCTION public.setoran_buku_terbuka()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
  SELECT b.id
  FROM public.setoran_buku b
  WHERE NOT b.ditutup
  ORDER BY b.id
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.setoran_buka_jika_perlu()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
  v_tgl date;
BEGIN
  v_id := public.setoran_buku_terbuka();
  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;

  v_tgl := (timezone('Asia/Jakarta', clock_timestamp()))::date;

  INSERT INTO public.setoran_buku (tanggal, ditutup)
  VALUES (v_tgl, false)
  RETURNING id INTO v_id;

  INSERT INTO public.stok_opname (
    id_setoran_buku, tanggal, id_barang, nama_barang, stok_awal, qty_packed
  )
  SELECT
    v_id,
    v_tgl,
    b.id_barang,
    b.nama_barang,
    GREATEST(COALESCE(b.stok, 0), 0),
    0
  FROM public.barang b
  WHERE btrim(b.id_barang) <> '';

  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.serahkan_stok_jika_gudang_kosong()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.absensi a
    WHERE a.waktu_keluar IS NULL
      AND a.peran IN ('gudang', 'admin')
  ) THEN
    RETURN;
  END IF;

  v_id := public.setoran_buku_terbuka();
  IF v_id IS NULL THEN
    RETURN;
  END IF;

  UPDATE public.barang b
  SET stok = GREATEST(0, COALESCE(so.stok_fisik, so.stok_hitung, 0))
  FROM public.stok_opname so
  WHERE so.id_setoran_buku = v_id
    AND so.id_barang = b.id_barang;
END;
$$;

CREATE OR REPLACE FUNCTION public.gudang_scan_absensi(
  p_keluar boolean,
  p_latitude double precision,
  p_longitude double precision,
  p_waktu timestamptz
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_email text;
  v_peran text;
  v_rute text;
  v_now timestamptz;
  v_tanggal date;
  v_id bigint;
  v_buku bigint;
BEGIN
  IF NOT public.gudang_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;

  IF p_waktu IS NULL THEN
    RAISE EXCEPTION 'Waktu HP kosong';
  END IF;
  IF abs(extract(epoch FROM (p_waktu - clock_timestamp()))) > 180 THEN
    RAISE EXCEPTION 'Jam HP tidak sesuai waktu Jakarta. Nyalakan waktu otomatis, lalu scan lagi.';
  END IF;
  v_now := p_waktu;

  PERFORM public.pastikan_di_gudang(p_latitude, p_longitude);

  v_email := lower(btrim(COALESCE(auth.jwt() ->> 'email', '')));
  IF v_email = '' THEN
    RAISE EXCEPTION 'Email sesi kosong.';
  END IF;

  SELECT lower(btrim(u.peran)), u.rute INTO v_peran, v_rute
  FROM public.users u
  WHERE lower(btrim(u.email)) = v_email
  LIMIT 1;

  IF v_peran IS NULL OR v_peran NOT IN ('gudang', 'admin') THEN
    RAISE EXCEPTION 'Hanya gudang atau admin yang boleh scan absensi di aplikasi ini.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221019);
  PERFORM pg_advisory_xact_lock(hashtext(v_email));

  IF p_keluar THEN
    SELECT a.id INTO v_id
    FROM public.absensi a
    WHERE lower(btrim(a.email)) = v_email
      AND a.waktu_keluar IS NULL
    ORDER BY a.waktu_masuk DESC NULLS LAST, a.id DESC
    LIMIT 1
    FOR UPDATE;

    IF v_id IS NULL THEN
      RAISE EXCEPTION 'Belum scan masuk.';
    END IF;

    UPDATE public.absensi
    SET waktu_keluar = v_now
    WHERE id = v_id
      AND waktu_keluar IS NULL;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Sudah scan pulang.';
    END IF;

    SELECT a.tanggal INTO v_tanggal FROM public.absensi a WHERE a.id = v_id;
    PERFORM public.serahkan_stok_jika_gudang_kosong();

    RETURN jsonb_build_object(
      'id_absensi', v_id,
      'tanggal', v_tanggal,
      'waktu', v_now,
      'keluar', true
    );
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.absensi a
    WHERE lower(btrim(a.email)) = v_email
      AND a.waktu_keluar IS NULL
  ) THEN
    RAISE EXCEPTION 'Sudah scan masuk.';
  END IF;

  v_buku := public.setoran_buka_jika_perlu();
  SELECT b.tanggal INTO v_tanggal
  FROM public.setoran_buku b
  WHERE b.id = v_buku;

  INSERT INTO public.absensi (
    email, peran, rute, tanggal, waktu_masuk, waktu_keluar, id_setoran_buku
  ) VALUES (
    v_email, v_peran, v_rute, v_tanggal, v_now, NULL, v_buku
  )
  RETURNING id INTO v_id;

  RETURN jsonb_build_object(
    'id_absensi', v_id,
    'tanggal', v_tanggal,
    'waktu', v_now,
    'keluar', false,
    'id_setoran_buku', v_buku
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.gudang_pack_nota(
  p_id_transaksi text,
  p_baris jsonb
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_status text;
  v_actual timestamptz;
  v_cap bigint;
  v_tutup boolean;
  v_buku bigint;
  v_tgl date;
  v_item jsonb;
  v_sku text;
  v_qty integer;
  v_sisa numeric;
  v_maks numeric;
  v_lama integer;
  v_delta integer;
  v_jual integer;
  v_beli integer;
  v_nama text;
  v_grup text;
  v_min1 integer; v_jual1 integer;
  v_min2 integer; v_jual2 integer;
  v_min3 integer; v_jual3 integer;
  v_min4 integer; v_jual4 integer;
  v_min5 integer; v_jual5 integer;
  v_ada boolean;
  v_ada_isi boolean;
BEGIN
  IF NOT public.gudang_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  IF public.gudang_id_absensi_saya() IS NULL THEN
    RAISE EXCEPTION 'Belum scan masuk.';
  END IF;
  IF btrim(COALESCE(p_id_transaksi, '')) = '' THEN
    RAISE EXCEPTION 'id_transaksi wajib.';
  END IF;
  IF p_baris IS NULL OR jsonb_typeof(p_baris) <> 'array' THEN
    RAISE EXCEPTION 'Daftar packing wajib.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221019);

  SELECT t.status, t.waktu_actual, t.id_setoran_buku
  INTO v_status, v_actual, v_cap
  FROM public.transaksi t
  WHERE t.id_transaksi = p_id_transaksi
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Nota tidak ada.';
  END IF;
  IF v_status = 'batal' THEN
    RAISE EXCEPTION 'Nota batal tidak bisa di packing.';
  END IF;
  IF v_actual IS NOT NULL OR v_status = 'terkirim' THEN
    RAISE EXCEPTION 'Nota sudah terkunci. Packing tidak bisa diubah.';
  END IF;

  IF v_cap IS NOT NULL THEN
    SELECT b.ditutup, b.tanggal INTO v_tutup, v_tgl
    FROM public.setoran_buku b
    WHERE b.id = v_cap;
    IF COALESCE(v_tutup, true) THEN
      RAISE EXCEPTION 'Nota sudah di buku tertutup. Packing tidak bisa diubah.';
    END IF;
    v_buku := v_cap;
  ELSE
    v_buku := public.setoran_buka_jika_perlu();
    SELECT b.tanggal INTO v_tgl FROM public.setoran_buku b WHERE b.id = v_buku;
  END IF;

  FOR v_item IN SELECT value FROM jsonb_array_elements(p_baris)
  LOOP
    v_sku := btrim(COALESCE(v_item ->> 'id_barang', ''));
    IF v_sku = '' THEN
      CONTINUE;
    END IF;
    v_qty := COALESCE((v_item ->> 'qty_packed')::integer, 0);
    IF v_qty < 0 THEN
      RAISE EXCEPTION 'Qty packing tidak boleh negatif (SKU %).', v_sku;
    END IF;

    SELECT
      b.id_barang,
      b.nama_barang,
      COALESCE(b.harga_jual, 0),
      GREATEST(COALESCE(b.harga_beli, 0), 0),
      b.id_grup,
      b.min_strat_1, b.jual_strat_1, b.min_strat_2, b.jual_strat_2,
      b.min_strat_3, b.jual_strat_3, b.min_strat_4, b.jual_strat_4,
      b.min_strat_5, b.jual_strat_5
    INTO
      v_sku, v_nama, v_jual, v_beli, v_grup,
      v_min1, v_jual1, v_min2, v_jual2,
      v_min3, v_jual3, v_min4, v_jual4,
      v_min5, v_jual5
    FROM public.barang b
    WHERE lower(b.id_barang) = lower(v_sku)
    FOR UPDATE;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'SKU % tidak ada di barang.', v_sku;
    END IF;

    SELECT true, i.qty_packed INTO v_ada, v_lama
    FROM public.transaksi_items i
    WHERE i.id_transaksi = p_id_transaksi
      AND i.id_barang = v_sku
    FOR UPDATE;
    IF NOT FOUND THEN
      v_ada := false;
      v_lama := 0;
      IF v_qty <= 0 THEN
        CONTINUE;
      END IF;
    END IF;

    INSERT INTO public.stok_opname (
      id_setoran_buku, tanggal, id_barang, nama_barang, stok_awal, qty_packed
    )
    SELECT
      v_buku,
      v_tgl,
      v_sku,
      v_nama,
      GREATEST(COALESCE(b.stok, 0), 0),
      0
    FROM public.barang b
    WHERE b.id_barang = v_sku
      AND NOT EXISTS (
        SELECT 1
        FROM public.stok_opname so
        WHERE so.id_setoran_buku = v_buku
          AND so.id_barang = v_sku
      );

    SELECT so.stok_hitung INTO v_sisa
    FROM public.stok_opname so
    WHERE so.id_setoran_buku = v_buku
      AND so.id_barang = v_sku
    FOR UPDATE;

    v_sisa := COALESCE(v_sisa, 0);
    v_maks := v_sisa + COALESCE(v_lama, 0);
    IF v_maks < COALESCE(v_lama, 0) THEN
      v_maks := COALESCE(v_lama, 0);
    END IF;
    IF v_qty > v_maks THEN
      RAISE EXCEPTION 'Sisa stok tidak cukup (SKU %).', v_sku;
    END IF;

    IF NOT v_ada THEN
      INSERT INTO public.transaksi_items (
        id_transaksi, id_barang, id_grup, nama_barang, harga_beli, harga_jual,
        qty_order, harga_jual_order,
        qty_packed, harga_jual_packed,
        min_strat_1, jual_strat_1, min_strat_2, jual_strat_2,
        min_strat_3, jual_strat_3, min_strat_4, jual_strat_4,
        min_strat_5, jual_strat_5
      ) VALUES (
        p_id_transaksi, v_sku, v_grup, v_nama, v_beli, v_jual,
        0, v_jual,
        v_qty, v_jual,
        COALESCE(v_min1, 0), COALESCE(v_jual1, 0),
        COALESCE(v_min2, 0), COALESCE(v_jual2, 0),
        COALESCE(v_min3, 0), COALESCE(v_jual3, 0),
        COALESCE(v_min4, 0), COALESCE(v_jual4, 0),
        COALESCE(v_min5, 0), COALESCE(v_jual5, 0)
      );
    END IF;

    v_delta := v_qty - COALESCE(v_lama, 0);
    IF v_delta <> 0 THEN
      UPDATE public.stok_opname
      SET
        qty_packed = qty_packed + v_delta,
        stok_fisik = CASE
          WHEN stok_fisik IS NULL THEN NULL
          ELSE GREATEST(0, stok_fisik - v_delta)
        END
      WHERE id_setoran_buku = v_buku
        AND id_barang = v_sku;
    END IF;

    IF v_ada THEN
      UPDATE public.transaksi_items
      SET
        qty_packed = v_qty,
        harga_jual_packed = COALESCE(harga_jual_packed, harga_jual_order, v_jual, 0)
      WHERE id_transaksi = p_id_transaksi
        AND id_barang = v_sku;
    END IF;
  END LOOP;

  UPDATE public.transaksi_items i
  SET
    qty_packed = 0,
    harga_jual_packed = COALESCE(i.harga_jual_order, 0)
  WHERE i.id_transaksi = p_id_transaksi
    AND i.qty_packed IS NULL;

  UPDATE public.transaksi_items i
  SET harga_jual_packed = public.harga_jual_strata(
    COALESCE(i.harga_jual, 0),
    (
      SELECT COALESCE(sum(x.qty_packed), 0)::integer
      FROM public.transaksi_items x
      WHERE x.id_transaksi = i.id_transaksi
        AND COALESCE(NULLIF(btrim(x.id_grup), ''), x.id_barang)
          = COALESCE(NULLIF(btrim(i.id_grup), ''), i.id_barang)
    ),
    i.min_strat_1, i.jual_strat_1,
    i.min_strat_2, i.jual_strat_2,
    i.min_strat_3, i.jual_strat_3,
    i.min_strat_4, i.jual_strat_4,
    i.min_strat_5, i.jual_strat_5
  )
  WHERE i.id_transaksi = p_id_transaksi
    AND i.qty_packed IS NOT NULL;

  SELECT EXISTS (
    SELECT 1
    FROM public.transaksi_items i
    WHERE i.id_transaksi = p_id_transaksi
      AND COALESCE(i.qty_packed, 0) > 0
  ) INTO v_ada_isi;

  IF v_ada_isi THEN
    UPDATE public.transaksi
    SET
      waktu_packed = COALESCE(waktu_packed, clock_timestamp()),
      status = CASE WHEN status = 'diproses' THEN 'dikirim' ELSE status END,
      id_setoran_buku = COALESCE(id_setoran_buku, v_buku)
    WHERE id_transaksi = p_id_transaksi;
  ELSE
    UPDATE public.transaksi
    SET
      status = 'batal',
      pending = false,
      waktu_packed = COALESCE(waktu_packed, clock_timestamp()),
      id_setoran_buku = COALESCE(id_setoran_buku, v_buku)
    WHERE id_transaksi = p_id_transaksi;
  END IF;
END;
$$;

-- Katalog gudang: sisa buku terbuka, bukan master semata.
CREATE OR REPLACE FUNCTION public.gudang_barang_katalog()
RETURNS TABLE (
  id_barang text,
  id_grup text,
  nama_barang text,
  kategori text,
  stok numeric,
  harga_beli integer,
  harga_jual integer,
  min_strat_1 integer,
  jual_strat_1 integer,
  min_strat_2 integer,
  jual_strat_2 integer,
  min_strat_3 integer,
  jual_strat_3 integer,
  min_strat_4 integer,
  jual_strat_4 integer,
  min_strat_5 integer,
  jual_strat_5 integer
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
BEGIN
  IF NOT public.gudang_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  v_buku := public.setoran_buku_terbuka();
  RETURN QUERY
  SELECT
    b.id_barang,
    b.id_grup,
    b.nama_barang,
    b.kategori,
    COALESCE(so.stok_hitung, b.stok),
    b.harga_beli,
    b.harga_jual,
    b.min_strat_1,
    b.jual_strat_1,
    b.min_strat_2,
    b.jual_strat_2,
    b.min_strat_3,
    b.jual_strat_3,
    b.min_strat_4,
    b.jual_strat_4,
    b.min_strat_5,
    b.jual_strat_5
  FROM public.barang b
  LEFT JOIN public.stok_opname so
    ON so.id_setoran_buku = v_buku
   AND so.id_barang = b.id_barang
  WHERE btrim(b.id_barang) <> ''
  ORDER BY lower(b.nama_barang), b.id_barang
  LIMIT 8000;
END;
$$;

CREATE OR REPLACE FUNCTION public.gudang_barang_cari(p_kata text)
RETURNS TABLE (
  id_barang text,
  id_grup text,
  nama_barang text,
  kategori text,
  stok numeric,
  harga_beli integer,
  harga_jual integer,
  min_strat_1 integer,
  jual_strat_1 integer,
  min_strat_2 integer,
  jual_strat_2 integer,
  min_strat_3 integer,
  jual_strat_3 integer,
  min_strat_4 integer,
  jual_strat_4 integer,
  min_strat_5 integer,
  jual_strat_5 integer
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_q text := lower(btrim(COALESCE(p_kata, '')));
  v_buku bigint;
BEGIN
  IF NOT public.gudang_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  v_buku := public.setoran_buku_terbuka();
  RETURN QUERY
  SELECT
    b.id_barang,
    b.id_grup,
    b.nama_barang,
    b.kategori,
    COALESCE(so.stok_hitung, b.stok),
    b.harga_beli,
    b.harga_jual,
    b.min_strat_1,
    b.jual_strat_1,
    b.min_strat_2,
    b.jual_strat_2,
    b.min_strat_3,
    b.jual_strat_3,
    b.min_strat_4,
    b.jual_strat_4,
    b.min_strat_5,
    b.jual_strat_5
  FROM public.barang b
  LEFT JOIN public.stok_opname so
    ON so.id_setoran_buku = v_buku
   AND so.id_barang = b.id_barang
  WHERE btrim(b.id_barang) <> ''
    AND (
      v_q = ''
      OR lower(b.nama_barang) LIKE '%' || v_q || '%'
      OR lower(b.id_barang) LIKE '%' || v_q || '%'
    )
  ORDER BY lower(b.nama_barang), b.id_barang
  LIMIT 80;
END;
$$;

CREATE OR REPLACE FUNCTION public.gudang_barang_banyak(p_id jsonb)
RETURNS TABLE (
  id_barang text,
  id_grup text,
  nama_barang text,
  kategori text,
  stok numeric,
  harga_beli integer,
  harga_jual integer,
  min_strat_1 integer,
  jual_strat_1 integer,
  min_strat_2 integer,
  jual_strat_2 integer,
  min_strat_3 integer,
  jual_strat_3 integer,
  min_strat_4 integer,
  jual_strat_4 integer,
  min_strat_5 integer,
  jual_strat_5 integer
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
BEGIN
  IF NOT public.gudang_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  IF p_id IS NULL OR jsonb_typeof(p_id) <> 'array' THEN
    RETURN;
  END IF;
  v_buku := public.setoran_buku_terbuka();
  RETURN QUERY
  SELECT
    b.id_barang,
    b.id_grup,
    b.nama_barang,
    b.kategori,
    COALESCE(so.stok_hitung, b.stok),
    b.harga_beli,
    b.harga_jual,
    b.min_strat_1,
    b.jual_strat_1,
    b.min_strat_2,
    b.jual_strat_2,
    b.min_strat_3,
    b.jual_strat_3,
    b.min_strat_4,
    b.jual_strat_4,
    b.min_strat_5,
    b.jual_strat_5
  FROM public.barang b
  LEFT JOIN public.stok_opname so
    ON so.id_setoran_buku = v_buku
   AND so.id_barang = b.id_barang
  WHERE b.id_barang IN (
    SELECT jsonb_array_elements_text(p_id)
  )
  ORDER BY lower(b.nama_barang), b.id_barang;
END;
$$;

-- Konfirmasi admin: barang.stok = stok_fisik (tanpa kolom qty terpisah).
CREATE OR REPLACE FUNCTION public.admin_konfirmasi_opname(p_id_setoran_buku bigint)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_n integer := 0;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh konfirmasi opname.';
  END IF;
  IF p_id_setoran_buku IS NULL THEN
    RAISE EXCEPTION 'Buku kosong.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221019);

  UPDATE public.barang b
  SET stok = GREATEST(0, so.stok_fisik)
  FROM public.stok_opname so
  WHERE so.id_setoran_buku = p_id_setoran_buku
    AND so.id_barang = b.id_barang
    AND so.stok_fisik IS NOT NULL;

  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$$;

-- Tutup buku. Stok master = fisik jika ada, selain itu sisa hitung.
-- Scan/packing berikutnya membuka buku baru.
CREATE OR REPLACE FUNCTION public.admin_tutup_setoran_buku()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh menutup buku.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221019);

  v_id := public.setoran_buku_terbuka();
  IF v_id IS NULL THEN
    RAISE EXCEPTION 'Tidak ada buku terbuka.';
  END IF;

  UPDATE public.barang b
  SET stok = GREATEST(0, COALESCE(so.stok_fisik, so.stok_hitung, 0))
  FROM public.stok_opname so
  WHERE so.id_setoran_buku = v_id
    AND so.id_barang = b.id_barang;

  UPDATE public.setoran_buku
  SET
    ditutup = true,
    waktu_tutup = clock_timestamp()
  WHERE id = v_id
    AND NOT ditutup;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.setoran_buku_terbuka() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.setoran_buku_terbuka()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.setoran_buka_jika_perlu() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.setoran_buka_jika_perlu()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.serahkan_stok_jika_gudang_kosong() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.serahkan_stok_jika_gudang_kosong()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_scan_absensi(boolean, double precision, double precision, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_scan_absensi(boolean, double precision, double precision, timestamptz)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_pack_nota(text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_pack_nota(text, jsonb)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_barang_katalog() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_barang_katalog()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_barang_cari(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_barang_cari(text)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.gudang_barang_banyak(jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.gudang_barang_banyak(jsonb)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_konfirmasi_opname(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_konfirmasi_opname(bigint)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_tutup_setoran_buku() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_tutup_setoran_buku()
  TO authenticated, postgres, service_role;

NOTIFY pgrst, 'reload schema';
