-- Putusan selisih opname: kasbon / beban / margin plus.
-- Plus otomatis ke pool gaji saat tutup buku. Minus wajib diputuskan dulu.
-- Jalankan SETELAH 019. Boleh diulang.

ALTER TABLE public.stok_opname
  ADD COLUMN IF NOT EXISTS putusan text,
  ADD COLUMN IF NOT EXISTS nilai_putusan integer,
  ADD COLUMN IF NOT EXISTS harga_beli_putusan integer,
  ADD COLUMN IF NOT EXISTS qty_selisih_putusan numeric(14, 4),
  ADD COLUMN IF NOT EXISTS kasbon_email text,
  ADD COLUMN IF NOT EXISTS kasbon_nama text,
  ADD COLUMN IF NOT EXISTS waktu_putusan timestamptz;

ALTER TABLE public.stok_opname
  DROP CONSTRAINT IF EXISTS stok_opname_putusan_chk;
ALTER TABLE public.stok_opname
  ADD CONSTRAINT stok_opname_putusan_chk CHECK (
    putusan IS NULL
    OR (
      putusan IN ('kasbon', 'beban', 'margin_plus')
      AND nilai_putusan IS NOT NULL
      AND nilai_putusan >= 0
      AND harga_beli_putusan IS NOT NULL
      AND harga_beli_putusan >= 0
      AND (
        putusan <> 'kasbon'
        OR (
          kasbon_email IS NOT NULL
          AND btrim(kasbon_email) <> ''
          AND kasbon_nama IS NOT NULL
          AND btrim(kasbon_nama) <> ''
        )
      )
    )
  );

COMMENT ON COLUMN public.stok_opname.putusan IS
  'kasbon = utang karyawan. beban = potong margin gaji. margin_plus = tambah margin gaji.';

CREATE TABLE IF NOT EXISTS public.kasbon (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL REFERENCES public.users (email),
  nama text NOT NULL,
  nilai integer NOT NULL,
  id_setoran_buku bigint NOT NULL REFERENCES public.setoran_buku (id),
  id_barang text NOT NULL,
  waktu timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT kasbon_nilai_chk CHECK (nilai > 0),
  CONSTRAINT kasbon_nama_chk CHECK (btrim(nama) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS kasbon_buku_sku_uidx
  ON public.kasbon (id_setoran_buku, id_barang);
CREATE INDEX IF NOT EXISTS kasbon_email_idx
  ON public.kasbon (email, waktu DESC);

COMMENT ON TABLE public.kasbon IS
  'Utang karyawan dari selisih opname kurang. Satu baris per SKU per buku.';

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.kasbon
  TO postgres, service_role;
GRANT SELECT ON TABLE public.kasbon TO authenticated;
REVOKE ALL ON TABLE public.kasbon FROM anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;

ALTER TABLE public.kasbon ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kasbon FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS kasbon_select_admin ON public.kasbon;
CREATE POLICY kasbon_select_admin
  ON public.kasbon
  FOR SELECT
  TO authenticated
  USING (public.admin_sedang_login());

CREATE OR REPLACE FUNCTION public.stok_opname_bersih_putusan()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.putusan IS NULL THEN
    RETURN NEW;
  END IF;
  IF NEW.selisih IS DISTINCT FROM OLD.selisih
     OR NEW.stok_fisik IS DISTINCT FROM OLD.stok_fisik THEN
    DELETE FROM public.kasbon k
    WHERE k.id_setoran_buku = NEW.id_setoran_buku
      AND k.id_barang = NEW.id_barang;
    NEW.putusan := NULL;
    NEW.nilai_putusan := NULL;
    NEW.harga_beli_putusan := NULL;
    NEW.qty_selisih_putusan := NULL;
    NEW.kasbon_email := NULL;
    NEW.kasbon_nama := NULL;
    NEW.waktu_putusan := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS stok_opname_bersih_putusan_trg ON public.stok_opname;
CREATE TRIGGER stok_opname_bersih_putusan_trg
  BEFORE UPDATE OF stok_fisik, qty_packed, stok_awal ON public.stok_opname
  FOR EACH ROW
  EXECUTE PROCEDURE public.stok_opname_bersih_putusan();

CREATE OR REPLACE FUNCTION public.admin_users_kasbon()
RETURNS TABLE (email text, nama text, peran text)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;
  RETURN QUERY
  SELECT u.email, u.nama, u.peran
  FROM public.users u
  ORDER BY lower(u.nama), u.email;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_opname_putusan(
  p_id_setoran_buku bigint,
  p_id_barang text,
  p_jenis text,
  p_email text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_tutup boolean;
  v_jenis text;
  v_sku text;
  v_selisih numeric;
  v_harga integer;
  v_nilai integer;
  v_email text;
  v_nama text;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh memutuskan selisih.';
  END IF;
  IF p_id_setoran_buku IS NULL OR btrim(COALESCE(p_id_barang, '')) = '' THEN
    RAISE EXCEPTION 'Buku atau SKU kosong.';
  END IF;

  v_jenis := lower(btrim(COALESCE(p_jenis, '')));
  IF v_jenis NOT IN ('kasbon', 'beban') THEN
    RAISE EXCEPTION 'Jenis putusan wajib kasbon atau beban.';
  END IF;

  SELECT b.ditutup INTO v_tutup
  FROM public.setoran_buku b
  WHERE b.id = p_id_setoran_buku;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Buku tidak ada.';
  END IF;
  IF COALESCE(v_tutup, false) THEN
    RAISE EXCEPTION 'Buku sudah ditutup.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221019);

  SELECT so.id_barang, so.selisih, GREATEST(COALESCE(b.harga_beli, 0), 0)::integer
  INTO v_sku, v_selisih, v_harga
  FROM public.stok_opname so
  LEFT JOIN public.barang b ON b.id_barang = so.id_barang
  WHERE so.id_setoran_buku = p_id_setoran_buku
    AND so.id_barang = btrim(p_id_barang);
  IF v_sku IS NULL THEN
    RAISE EXCEPTION 'SKU tidak ada di buku ini.';
  END IF;
  IF v_selisih IS NULL OR v_selisih >= 0 THEN
    RAISE EXCEPTION 'Hanya selisih kurang yang dipilih kasbon atau beban.';
  END IF;

  v_nilai := round(abs(v_selisih) * v_harga)::integer;

  IF v_jenis = 'kasbon' THEN
    v_email := lower(btrim(COALESCE(p_email, '')));
    IF v_email = '' THEN
      RAISE EXCEPTION 'Pilih karyawan untuk kasbon.';
    END IF;
    SELECT u.nama INTO v_nama
    FROM public.users u
    WHERE u.email = v_email;
    IF v_nama IS NULL THEN
      RAISE EXCEPTION 'Karyawan tidak ada.';
    END IF;
    IF v_nilai < 1 THEN
      RAISE EXCEPTION 'Nilai kasbon harus lebih dari nol. Cek harga beli.';
    END IF;
  ELSE
    v_email := NULL;
    v_nama := NULL;
  END IF;

  UPDATE public.stok_opname
  SET
    putusan = v_jenis,
    nilai_putusan = v_nilai,
    harga_beli_putusan = v_harga,
    qty_selisih_putusan = v_selisih,
    kasbon_email = v_email,
    kasbon_nama = v_nama,
    waktu_putusan = clock_timestamp()
  WHERE id_setoran_buku = p_id_setoran_buku
    AND id_barang = v_sku;

  DELETE FROM public.kasbon
  WHERE id_setoran_buku = p_id_setoran_buku
    AND id_barang = v_sku;

  IF v_jenis = 'kasbon' THEN
    INSERT INTO public.kasbon (
      email, nama, nilai, id_setoran_buku, id_barang
    ) VALUES (
      v_email, v_nama, v_nilai, p_id_setoran_buku, v_sku
    );
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_opname_ringkas()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
  v_tgl date;
  v_tutup boolean;
  v_total integer := 0;
  v_fisik integer := 0;
  v_selisih integer := 0;
  v_nilai bigint := 0;
  v_minus_belum integer := 0;
  v_kasbon bigint := 0;
  v_beban bigint := 0;
  v_plus bigint := 0;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;

  v_id := public.setoran_buku_terbuka();
  IF v_id IS NULL THEN
    SELECT b.id, b.tanggal, b.ditutup
    INTO v_id, v_tgl, v_tutup
    FROM public.setoran_buku b
    ORDER BY b.id DESC
    LIMIT 1;
  ELSE
    SELECT b.tanggal, b.ditutup
    INTO v_tgl, v_tutup
    FROM public.setoran_buku b
    WHERE b.id = v_id;
  END IF;

  IF v_id IS NULL THEN
    RETURN jsonb_build_object(
      'ada_buku', false,
      'id_setoran_buku', NULL,
      'tanggal', NULL,
      'ditutup', false,
      'sku_total', 0,
      'sku_fisik', 0,
      'sku_selisih', 0,
      'nilai_selisih', 0,
      'sku_minus_belum', 0,
      'nilai_kasbon', 0,
      'nilai_beban', 0,
      'nilai_margin_plus', 0
    );
  END IF;

  SELECT
    count(*)::integer,
    count(*) FILTER (WHERE so.stok_fisik IS NOT NULL)::integer,
    count(*) FILTER (
      WHERE so.stok_fisik IS NOT NULL AND COALESCE(so.selisih, 0) <> 0
    )::integer,
    coalesce(sum(
      CASE
        WHEN so.stok_fisik IS NULL THEN 0
        ELSE round(COALESCE(so.selisih, 0) * COALESCE(b.harga_beli, 0))
      END
    ), 0)::bigint,
    count(*) FILTER (
      WHERE so.stok_fisik IS NOT NULL
        AND COALESCE(so.selisih, 0) < 0
        AND so.putusan IS DISTINCT FROM 'kasbon'
        AND so.putusan IS DISTINCT FROM 'beban'
    )::integer,
    coalesce(sum(so.nilai_putusan) FILTER (WHERE so.putusan = 'kasbon'), 0)::bigint,
    coalesce(sum(so.nilai_putusan) FILTER (WHERE so.putusan = 'beban'), 0)::bigint,
    coalesce(sum(
      CASE
        WHEN so.stok_fisik IS NOT NULL AND COALESCE(so.selisih, 0) > 0
          THEN round(so.selisih * COALESCE(b.harga_beli, 0))
        ELSE 0
      END
    ), 0)::bigint
  INTO v_total, v_fisik, v_selisih, v_nilai, v_minus_belum, v_kasbon, v_beban, v_plus
  FROM public.stok_opname so
  LEFT JOIN public.barang b ON b.id_barang = so.id_barang
  WHERE so.id_setoran_buku = v_id;

  RETURN jsonb_build_object(
    'ada_buku', true,
    'id_setoran_buku', v_id,
    'tanggal', v_tgl,
    'ditutup', COALESCE(v_tutup, false),
    'sku_total', v_total,
    'sku_fisik', v_fisik,
    'sku_selisih', v_selisih,
    'nilai_selisih', v_nilai,
    'sku_minus_belum', v_minus_belum,
    'nilai_kasbon', v_kasbon,
    'nilai_beban', v_beban,
    'nilai_margin_plus', v_plus
  );
END;
$$;

DROP FUNCTION IF EXISTS public.admin_opname_lihat(bigint);

CREATE OR REPLACE FUNCTION public.admin_opname_lihat(p_id_setoran_buku bigint)
RETURNS TABLE (
  id_barang text,
  nama_barang text,
  stok_awal numeric,
  qty_packed numeric,
  stok_hitung numeric,
  stok_fisik numeric,
  selisih numeric,
  nilai_selisih integer,
  harga_beli integer,
  dicek_stok_oleh text,
  putusan text,
  kasbon_email text,
  kasbon_nama text,
  nilai_putusan integer
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;
  IF p_id_setoran_buku IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    so.id_barang,
    so.nama_barang,
    so.stok_awal,
    so.qty_packed,
    so.stok_hitung,
    so.stok_fisik,
    so.selisih,
    round(COALESCE(so.selisih, 0) * COALESCE(b.harga_beli, 0))::integer,
    COALESCE(b.harga_beli, 0),
    so.dicek_stok_oleh,
    so.putusan,
    so.kasbon_email,
    so.kasbon_nama,
    so.nilai_putusan
  FROM public.stok_opname so
  LEFT JOIN public.barang b ON b.id_barang = so.id_barang
  WHERE so.id_setoran_buku = p_id_setoran_buku
    AND so.stok_fisik IS NOT NULL
    AND COALESCE(so.selisih, 0) <> 0
  ORDER BY
    CASE WHEN COALESCE(so.selisih, 0) < 0 THEN 0 ELSE 1 END,
    lower(so.nama_barang),
    so.id_barang;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_tutup_setoran_buku()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
  v_sku text;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh menutup buku.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221019);

  v_id := public.setoran_buku_terbuka();
  IF v_id IS NULL THEN
    RAISE EXCEPTION 'Tidak ada buku terbuka.';
  END IF;

  SELECT so.id_barang
  INTO v_sku
  FROM public.stok_opname so
  WHERE so.id_setoran_buku = v_id
    AND so.stok_fisik IS NOT NULL
    AND COALESCE(so.selisih, 0) < 0
    AND so.putusan IS DISTINCT FROM 'kasbon'
    AND so.putusan IS DISTINCT FROM 'beban'
  ORDER BY lower(so.nama_barang)
  LIMIT 1;
  IF v_sku IS NOT NULL THEN
    RAISE EXCEPTION
      'Masih ada selisih kurang belum diputuskan (SKU %). Kasbon atau potong margin dulu.',
      v_sku;
  END IF;

  UPDATE public.stok_opname so
  SET
    putusan = 'margin_plus',
    nilai_putusan = round(so.selisih * GREATEST(COALESCE(b.harga_beli, 0), 0))::integer,
    harga_beli_putusan = GREATEST(COALESCE(b.harga_beli, 0), 0)::integer,
    qty_selisih_putusan = so.selisih,
    kasbon_email = NULL,
    kasbon_nama = NULL,
    waktu_putusan = clock_timestamp()
  FROM public.barang b
  WHERE so.id_setoran_buku = v_id
    AND so.id_barang = b.id_barang
    AND so.stok_fisik IS NOT NULL
    AND COALESCE(so.selisih, 0) > 0;

  PERFORM set_config('obos.boleh_tulis_stok', 'on', true);

  UPDATE public.barang b
  SET stok = GREATEST(0, COALESCE(so.stok_fisik, so.stok_hitung, 0))
  FROM public.stok_opname so
  WHERE so.id_setoran_buku = v_id
    AND so.id_barang = b.id_barang;

  UPDATE public.setoran_buku
  SET
    ditutup = true,
    waktu_tutup = clock_timestamp()
  WHERE id = v_id
    AND NOT ditutup;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_users_kasbon() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_users_kasbon()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_opname_putusan(bigint, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_opname_putusan(bigint, text, text, text)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_opname_ringkas() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_opname_ringkas()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_opname_lihat(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_opname_lihat(bigint)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_tutup_setoran_buku() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_tutup_setoran_buku()
  TO authenticated, postgres, service_role;

NOTIFY pgrst, 'reload schema';
