-- Barang masuk + supplier + supplier_harga + ongkir.
-- Tanpa buku: tulis barang.stok. Ada buku: geser stok_opname.
-- Harga katalog kelipatan 5; GREATEST jika supplier = id_supplier_utama.
-- Jalankan SETELAH 021. Boleh diulang.

ALTER TABLE public.barang
  ADD COLUMN IF NOT EXISTS id_supplier_utama integer;

CREATE TABLE IF NOT EXISTS public.supplier (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  CONSTRAINT supplier_nama_chk CHECK (btrim(nama) <> ''),
  CONSTRAINT supplier_nama_uk UNIQUE (nama)
);

CREATE TABLE IF NOT EXISTS public.supplier_harga (
  id_supplier integer NOT NULL REFERENCES public.supplier (id),
  id_barang text NOT NULL REFERENCES public.barang (id_barang),
  harga_beli integer NOT NULL DEFAULT 0,
  PRIMARY KEY (id_supplier, id_barang),
  CONSTRAINT supplier_harga_beli_chk CHECK (harga_beli >= 0)
);

CREATE TABLE IF NOT EXISTS public.barang_masuk (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  id_supplier integer NOT NULL REFERENCES public.supplier (id),
  id_barang text NOT NULL REFERENCES public.barang (id_barang),
  qty numeric(14, 4) NOT NULL DEFAULT 0,
  nilai integer NOT NULL DEFAULT 0,
  id_setoran_buku bigint REFERENCES public.setoran_buku (id),
  CONSTRAINT barang_masuk_qty_chk CHECK (qty > 0),
  CONSTRAINT barang_masuk_nilai_chk CHECK (nilai >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS barang_masuk_buku_uidx
  ON public.barang_masuk (id_setoran_buku, id_supplier, id_barang)
  WHERE id_setoran_buku IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS barang_masuk_tgl_uidx
  ON public.barang_masuk (tanggal, id_supplier, id_barang)
  WHERE id_setoran_buku IS NULL;

CREATE TABLE IF NOT EXISTS public.ongkir (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  id_supplier integer NOT NULL REFERENCES public.supplier (id),
  jumlah integer NOT NULL DEFAULT 0,
  id_setoran_buku bigint REFERENCES public.setoran_buku (id),
  CONSTRAINT ongkir_jumlah_chk CHECK (jumlah >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS ongkir_buku_uidx
  ON public.ongkir (id_setoran_buku, id_supplier)
  WHERE id_setoran_buku IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ongkir_tgl_uidx
  ON public.ongkir (tanggal, id_supplier)
  WHERE id_setoran_buku IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'barang_supplier_utama_fk'
  ) THEN
    ALTER TABLE public.barang
      ADD CONSTRAINT barang_supplier_utama_fk
      FOREIGN KEY (id_supplier_utama) REFERENCES public.supplier (id);
  END IF;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.supplier
  TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.supplier_harga
  TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.barang_masuk
  TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.ongkir
  TO postgres, service_role;
GRANT SELECT ON TABLE public.supplier TO authenticated;
GRANT SELECT ON TABLE public.supplier_harga TO authenticated;
GRANT SELECT ON TABLE public.barang_masuk TO authenticated;
GRANT SELECT ON TABLE public.ongkir TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public
  TO postgres, service_role;
REVOKE ALL ON TABLE public.supplier FROM anon;
REVOKE ALL ON TABLE public.supplier_harga FROM anon;
REVOKE ALL ON TABLE public.barang_masuk FROM anon;
REVOKE ALL ON TABLE public.ongkir FROM anon;

ALTER TABLE public.supplier ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier FORCE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_harga ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.supplier_harga FORCE ROW LEVEL SECURITY;
ALTER TABLE public.barang_masuk ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.barang_masuk FORCE ROW LEVEL SECURITY;
ALTER TABLE public.ongkir ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ongkir FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS supplier_select_admin ON public.supplier;
CREATE POLICY supplier_select_admin ON public.supplier
  FOR SELECT TO authenticated USING (public.admin_sedang_login());
DROP POLICY IF EXISTS supplier_harga_select_admin ON public.supplier_harga;
CREATE POLICY supplier_harga_select_admin ON public.supplier_harga
  FOR SELECT TO authenticated USING (public.admin_sedang_login());
DROP POLICY IF EXISTS barang_masuk_select_admin ON public.barang_masuk;
CREATE POLICY barang_masuk_select_admin ON public.barang_masuk
  FOR SELECT TO authenticated USING (public.admin_sedang_login());
DROP POLICY IF EXISTS ongkir_select_admin ON public.ongkir;
CREATE POLICY ongkir_select_admin ON public.ongkir
  FOR SELECT TO authenticated USING (public.admin_sedang_login());

CREATE OR REPLACE FUNCTION public.jual_dari_modal(p_beli integer)
RETURNS integer
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v integer;
BEGIN
  IF COALESCE(p_beli, 0) <= 0 THEN
    RETURN 0;
  END IF;
  v := (round(p_beli::numeric * 1.05 / 500) * 500)::integer;
  IF v <= p_beli THEN
    v := (p_beli / 500 + 1) * 500;
  END IF;
  RETURN v;
END;
$$;

CREATE OR REPLACE FUNCTION public.barang_id_berikut()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id text;
  v_pre text;
  v_num text;
  v_next integer;
BEGIN
  PERFORM pg_advisory_xact_lock(88112001);
  SELECT b.id_barang
  INTO v_id
  FROM public.barang b
  WHERE b.id_barang ~ '^[A-Za-z]+[0-9]+$'
  ORDER BY substring(b.id_barang from '([0-9]+)$')::integer DESC, b.id_barang DESC
  LIMIT 1;
  IF v_id IS NULL OR v_id !~ '^[A-Za-z]+[0-9]+$' THEN
    RETURN 'BR001';
  END IF;
  v_pre := substring(v_id from '^([A-Za-z]+)');
  v_num := substring(v_id from '([0-9]+)$');
  v_next := v_num::integer + 1;
  RETURN v_pre || lpad(v_next::text, GREATEST(length(v_num), length(v_next::text)), '0');
END;
$$;

CREATE OR REPLACE FUNCTION public.barang_masuk_lingkup(OUT o_buku bigint, OUT o_tgl date)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
BEGIN
  o_buku := public.setoran_buku_terbuka();
  IF o_buku IS NOT NULL THEN
    SELECT b.tanggal INTO o_tgl FROM public.setoran_buku b WHERE b.id = o_buku;
  ELSE
    o_tgl := (timezone('Asia/Jakarta', clock_timestamp()))::date;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.barang_masuk_geser_stok(p_id_barang text, p_delta numeric)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
  v_tgl date;
  v_nama text;
  v_delta numeric(14, 4);
BEGIN
  v_delta := round(COALESCE(p_delta, 0), 4);
  IF v_delta = 0 OR btrim(COALESCE(p_id_barang, '')) = '' THEN
    RETURN;
  END IF;
  v_buku := public.setoran_buku_terbuka();
  IF v_buku IS NULL THEN
    PERFORM set_config('obos.boleh_tulis_stok', 'on', true);
    UPDATE public.barang
    SET stok = GREATEST(0, COALESCE(stok, 0) + v_delta)
    WHERE id_barang = p_id_barang;
    RETURN;
  END IF;

  SELECT b.tanggal INTO v_tgl FROM public.setoran_buku b WHERE b.id = v_buku;
  SELECT b.nama_barang INTO v_nama FROM public.barang b WHERE b.id_barang = p_id_barang;
  IF v_nama IS NULL THEN
    RAISE EXCEPTION 'SKU % tidak ada di katalog.', p_id_barang;
  END IF;

  INSERT INTO public.stok_opname (
    id_setoran_buku, tanggal, id_barang, nama_barang, stok_awal, qty_packed
  )
  VALUES (v_buku, v_tgl, p_id_barang, v_nama, GREATEST(0, v_delta), 0)
  ON CONFLICT (id_setoran_buku, id_barang) DO UPDATE SET
    stok_awal = GREATEST(0, public.stok_opname.stok_awal + v_delta),
    stok_fisik = CASE
      WHEN public.stok_opname.stok_fisik IS NULL THEN NULL
      ELSE GREATEST(0, public.stok_opname.stok_fisik + v_delta)
    END;
END;
$$;

CREATE OR REPLACE FUNCTION public.barang_masuk_terapkan_harga(
  p_id_supplier integer,
  p_id_barang text,
  p_harga numeric
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_kat integer;
  v_utama integer;
BEGIN
  v_kat := (round(GREATEST(COALESCE(p_harga, 0), 0) / 5) * 5)::integer;
  IF v_kat < 1 THEN
    RETURN 0;
  END IF;
  INSERT INTO public.supplier_harga (id_supplier, id_barang, harga_beli)
  VALUES (p_id_supplier, p_id_barang, v_kat)
  ON CONFLICT (id_supplier, id_barang) DO UPDATE SET
    harga_beli = EXCLUDED.harga_beli;

  SELECT b.id_supplier_utama INTO v_utama
  FROM public.barang b
  WHERE b.id_barang = p_id_barang;

  IF v_utama IS NULL THEN
    UPDATE public.barang
    SET
      id_supplier_utama = p_id_supplier,
      harga_beli = GREATEST(harga_beli, v_kat),
      harga_jual = CASE
        WHEN GREATEST(harga_beli, v_kat) <> harga_beli
          OR harga_jual < 1
        THEN public.jual_dari_modal(GREATEST(harga_beli, v_kat))
        ELSE harga_jual
      END
    WHERE id_barang = p_id_barang;
  ELSIF v_utama = p_id_supplier THEN
    UPDATE public.barang
    SET
      harga_beli = GREATEST(harga_beli, v_kat),
      harga_jual = CASE
        WHEN GREATEST(harga_beli, v_kat) > harga_beli
        THEN public.jual_dari_modal(GREATEST(harga_beli, v_kat))
        ELSE harga_jual
      END
    WHERE id_barang = p_id_barang;
  END IF;
  RETURN v_kat;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_supplier_daftar()
RETURNS TABLE (id integer, nama text)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;
  RETURN QUERY
  SELECT s.id, s.nama
  FROM public.supplier s
  WHERE s.aktif
  ORDER BY lower(s.nama);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_supplier_tambah(p_nama text)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_nama text;
  v_id integer;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh menambah supplier.';
  END IF;
  v_nama := btrim(COALESCE(p_nama, ''));
  IF v_nama = '' THEN
    RAISE EXCEPTION 'Nama supplier wajib.';
  END IF;
  INSERT INTO public.supplier (nama, aktif)
  VALUES (v_nama, true)
  ON CONFLICT (nama) DO UPDATE SET aktif = true
  RETURNING public.supplier.id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_barang_cari(p_q text)
RETURNS TABLE (id_barang text, nama_barang text, harga_beli integer)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_q text;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;
  v_q := lower(btrim(COALESCE(p_q, '')));
  IF length(v_q) < 1 THEN
    RETURN;
  END IF;
  RETURN QUERY
  SELECT b.id_barang, b.nama_barang, b.harga_beli
  FROM public.barang b
  WHERE lower(b.id_barang) LIKE '%' || v_q || '%'
     OR lower(b.nama_barang) LIKE '%' || v_q || '%'
  ORDER BY lower(b.nama_barang)
  LIMIT 20;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_barang_masuk_ringkas()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
  v_tgl date;
  v_sku integer := 0;
  v_nilai bigint := 0;
  v_ongkir bigint := 0;
  v_supplier jsonb := '[]'::jsonb;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;
  SELECT o_buku, o_tgl INTO v_buku, v_tgl FROM public.barang_masuk_lingkup();
  SELECT
    count(*)::integer,
    coalesce(sum(m.nilai), 0)::bigint
  INTO v_sku, v_nilai
  FROM public.barang_masuk m
  WHERE (v_buku IS NOT NULL AND m.id_setoran_buku = v_buku)
     OR (v_buku IS NULL AND m.id_setoran_buku IS NULL AND m.tanggal = v_tgl);

  SELECT coalesce(sum(o.jumlah), 0)::bigint
  INTO v_ongkir
  FROM public.ongkir o
  WHERE (v_buku IS NOT NULL AND o.id_setoran_buku = v_buku)
     OR (v_buku IS NULL AND o.id_setoran_buku IS NULL AND o.tanggal = v_tgl);

  SELECT coalesce(jsonb_agg(x.obj ORDER BY lower(x.nama)), '[]'::jsonb)
  INTO v_supplier
  FROM (
    SELECT
      jsonb_build_object(
        'id', s.id,
        'nama', s.nama,
        'sku', coalesce(m.sku, 0),
        'nilai', coalesce(m.nilai, 0),
        'ongkir', coalesce(o.jumlah, 0)
      ) AS obj,
      s.nama
    FROM (
      SELECT m.id_supplier
      FROM public.barang_masuk m
      WHERE (v_buku IS NOT NULL AND m.id_setoran_buku = v_buku)
         OR (v_buku IS NULL AND m.id_setoran_buku IS NULL AND m.tanggal = v_tgl)
      UNION
      SELECT o.id_supplier
      FROM public.ongkir o
      WHERE (v_buku IS NOT NULL AND o.id_setoran_buku = v_buku)
         OR (v_buku IS NULL AND o.id_setoran_buku IS NULL AND o.tanggal = v_tgl)
    ) ids
    JOIN public.supplier s ON s.id = ids.id_supplier
    LEFT JOIN LATERAL (
      SELECT
        count(*)::integer AS sku,
        coalesce(sum(mm.nilai), 0)::bigint AS nilai
      FROM public.barang_masuk mm
      WHERE mm.id_supplier = s.id
        AND (
          (v_buku IS NOT NULL AND mm.id_setoran_buku = v_buku)
          OR (v_buku IS NULL AND mm.id_setoran_buku IS NULL AND mm.tanggal = v_tgl)
        )
    ) m ON true
    LEFT JOIN LATERAL (
      SELECT oo.jumlah
      FROM public.ongkir oo
      WHERE oo.id_supplier = s.id
        AND (
          (v_buku IS NOT NULL AND oo.id_setoran_buku = v_buku)
          OR (v_buku IS NULL AND oo.id_setoran_buku IS NULL AND oo.tanggal = v_tgl)
        )
    ) o ON true
  ) x;

  RETURN jsonb_build_object(
    'ada_buku', v_buku IS NOT NULL,
    'id_setoran_buku', v_buku,
    'tanggal', v_tgl,
    'sku', v_sku,
    'nilai', v_nilai,
    'ongkir', v_ongkir,
    'supplier', v_supplier
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_barang_masuk_lihat(p_id_supplier integer)
RETURNS TABLE (
  id_barang text,
  nama_barang text,
  qty numeric,
  nilai integer,
  harga_beli integer
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
  v_tgl date;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;
  IF COALESCE(p_id_supplier, 0) < 1 THEN
    RETURN;
  END IF;
  SELECT o_buku, o_tgl INTO v_buku, v_tgl FROM public.barang_masuk_lingkup();
  RETURN QUERY
  SELECT
    m.id_barang,
    b.nama_barang,
    m.qty,
    m.nilai,
    CASE WHEN m.qty > 0 THEN round(m.nilai / m.qty)::integer ELSE COALESCE(h.harga_beli, 0) END
  FROM public.barang_masuk m
  JOIN public.barang b ON b.id_barang = m.id_barang
  LEFT JOIN public.supplier_harga h
    ON h.id_supplier = m.id_supplier AND h.id_barang = m.id_barang
  WHERE m.id_supplier = p_id_supplier
    AND (
      (v_buku IS NOT NULL AND m.id_setoran_buku = v_buku)
      OR (v_buku IS NULL AND m.id_setoran_buku IS NULL AND m.tanggal = v_tgl)
    )
  ORDER BY lower(b.nama_barang);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_ongkir_lihat_supplier(p_id_supplier integer)
RETURNS integer
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
  v_tgl date;
  v integer;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;
  IF COALESCE(p_id_supplier, 0) < 1 THEN
    RETURN 0;
  END IF;
  SELECT o_buku, o_tgl INTO v_buku, v_tgl FROM public.barang_masuk_lingkup();
  SELECT o.jumlah INTO v
  FROM public.ongkir o
  WHERE o.id_supplier = p_id_supplier
    AND (
      (v_buku IS NOT NULL AND o.id_setoran_buku = v_buku)
      OR (v_buku IS NULL AND o.id_setoran_buku IS NULL AND o.tanggal = v_tgl)
    );
  RETURN COALESCE(v, 0);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_ongkir_simpan(p_id_supplier integer, p_jumlah integer)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
  v_tgl date;
  v_jml integer;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh menyimpan ongkir.';
  END IF;
  IF COALESCE(p_id_supplier, 0) < 1 THEN
    RAISE EXCEPTION 'Pilih supplier.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.supplier s WHERE s.id = p_id_supplier AND s.aktif) THEN
    RAISE EXCEPTION 'Supplier tidak aktif.';
  END IF;
  v_jml := GREATEST(COALESCE(p_jumlah, 0), 0);
  SELECT o_buku, o_tgl INTO v_buku, v_tgl FROM public.barang_masuk_lingkup();
  IF v_jml = 0 THEN
    DELETE FROM public.ongkir o
    WHERE o.id_supplier = p_id_supplier
      AND (
        (v_buku IS NOT NULL AND o.id_setoran_buku = v_buku)
        OR (v_buku IS NULL AND o.id_setoran_buku IS NULL AND o.tanggal = v_tgl)
      );
    RETURN;
  END IF;
  IF v_buku IS NOT NULL THEN
    INSERT INTO public.ongkir (tanggal, id_supplier, jumlah, id_setoran_buku)
    VALUES (v_tgl, p_id_supplier, v_jml, v_buku)
    ON CONFLICT (id_setoran_buku, id_supplier) WHERE id_setoran_buku IS NOT NULL
    DO UPDATE SET jumlah = EXCLUDED.jumlah;
  ELSE
    INSERT INTO public.ongkir (tanggal, id_supplier, jumlah, id_setoran_buku)
    VALUES (v_tgl, p_id_supplier, v_jml, NULL)
    ON CONFLICT (tanggal, id_supplier) WHERE id_setoran_buku IS NULL
    DO UPDATE SET jumlah = EXCLUDED.jumlah;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_barang_masuk_simpan(
  p_id_supplier integer,
  p_baris jsonb,
  p_ongkir integer DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  r jsonb;
  v_buku bigint;
  v_tgl date;
  v_kode text;
  v_kode_in text;
  v_nama text;
  v_nama_dasar text;
  v_satuan text;
  v_rincian text;
  v_kategori text;
  v_qty numeric(14, 4);
  v_harga numeric;
  v_nilai integer;
  v_baru boolean;
  v_n integer := 0;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh menyimpan barang masuk.';
  END IF;
  IF COALESCE(p_id_supplier, 0) < 1 THEN
    RAISE EXCEPTION 'Pilih supplier.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.supplier s WHERE s.id = p_id_supplier AND s.aktif) THEN
    RAISE EXCEPTION 'Supplier tidak aktif.';
  END IF;
  IF p_baris IS NULL OR jsonb_typeof(p_baris) <> 'array' THEN
    RAISE EXCEPTION 'Daftar barang wajib.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221020);
  SELECT o_buku, o_tgl INTO v_buku, v_tgl FROM public.barang_masuk_lingkup();

  FOR r IN SELECT value FROM jsonb_array_elements(p_baris)
  LOOP
    v_baru := COALESCE((r ->> 'baru')::boolean, false);
    v_kode := nullif(btrim(COALESCE(r ->> 'id_barang', r ->> 'kode_barang', '')), '');
    v_nama_dasar := btrim(COALESCE(r ->> 'nama', ''));
    v_satuan := btrim(COALESCE(r ->> 'satuan', ''));
    v_rincian := btrim(COALESCE(r ->> 'rincian', ''));
    v_kategori := btrim(COALESCE(r ->> 'kategori', ''));
    v_qty := round(GREATEST(COALESCE(replace(btrim(COALESCE(r ->> 'qty', '')), ',', '.')::numeric, 0), 0), 4);
    v_harga := GREATEST(COALESCE(replace(btrim(COALESCE(r ->> 'harga_beli', '')), ',', '.')::numeric, 0), 0);
    IF v_qty <= 0 OR v_harga <= 0 THEN
      CONTINUE;
    END IF;
    v_nilai := round(v_qty * v_harga)::integer;

    IF v_baru THEN
      IF v_nama_dasar = '' OR v_satuan = '' THEN
        RAISE EXCEPTION 'SKU baru wajib nama dan satuan.';
      END IF;
      v_nama := v_nama_dasar || ' /' || v_satuan;
      IF v_rincian <> '' THEN
        v_nama := v_nama || '/' || v_rincian;
      END IF;
      v_kode := public.barang_id_berikut();
      INSERT INTO public.barang (
        id_barang, nama_barang, kategori, stok, harga_beli, harga_jual, id_supplier_utama
      )
      VALUES (
        v_kode,
        v_nama,
        nullif(v_kategori, ''),
        0,
        0,
        0,
        p_id_supplier
      );
    ELSE
      IF v_kode IS NULL THEN
        RAISE EXCEPTION 'Kode barang kosong.';
      END IF;
      v_kode_in := v_kode;
      SELECT b.id_barang INTO v_kode
      FROM public.barang b
      WHERE lower(b.id_barang) = lower(v_kode_in);
      IF v_kode IS NULL THEN
        RAISE EXCEPTION 'Kode % tidak ada di katalog. SKU baru isi di form SKU baru.', v_kode_in;
      END IF;
    END IF;

    PERFORM public.barang_masuk_geser_stok(v_kode, v_qty);
    PERFORM public.barang_masuk_terapkan_harga(p_id_supplier, v_kode, v_harga);

    IF v_buku IS NOT NULL THEN
      INSERT INTO public.barang_masuk (
        tanggal, id_supplier, id_barang, qty, nilai, id_setoran_buku
      )
      VALUES (v_tgl, p_id_supplier, v_kode, v_qty, v_nilai, v_buku)
      ON CONFLICT (id_setoran_buku, id_supplier, id_barang)
      WHERE id_setoran_buku IS NOT NULL
      DO UPDATE SET
        qty = public.barang_masuk.qty + EXCLUDED.qty,
        nilai = public.barang_masuk.nilai + EXCLUDED.nilai;
    ELSE
      INSERT INTO public.barang_masuk (
        tanggal, id_supplier, id_barang, qty, nilai, id_setoran_buku
      )
      VALUES (v_tgl, p_id_supplier, v_kode, v_qty, v_nilai, NULL)
      ON CONFLICT (tanggal, id_supplier, id_barang)
      WHERE id_setoran_buku IS NULL
      DO UPDATE SET
        qty = public.barang_masuk.qty + EXCLUDED.qty,
        nilai = public.barang_masuk.nilai + EXCLUDED.nilai;
    END IF;
    v_n := v_n + 1;
  END LOOP;

  IF p_ongkir IS NOT NULL THEN
    PERFORM public.admin_ongkir_simpan(p_id_supplier, p_ongkir);
  END IF;
  RETURN v_n;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_barang_masuk_ubah(
  p_id_supplier integer,
  p_id_barang text,
  p_qty numeric,
  p_harga_beli numeric
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
  v_tgl date;
  v_kode text;
  v_qty numeric(14, 4);
  v_lama numeric(14, 4);
  v_harga numeric;
  v_nilai integer;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh mengubah barang masuk.';
  END IF;
  v_kode := nullif(btrim(COALESCE(p_id_barang, '')), '');
  v_qty := round(GREATEST(COALESCE(p_qty, 0), 0), 4);
  v_harga := GREATEST(COALESCE(p_harga_beli, 0), 0);
  IF COALESCE(p_id_supplier, 0) < 1 OR v_kode IS NULL OR v_qty <= 0 OR v_harga <= 0 THEN
    RAISE EXCEPTION 'Qty dan harga beli wajib lebih dari nol.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221020);
  SELECT o_buku, o_tgl INTO v_buku, v_tgl FROM public.barang_masuk_lingkup();

  SELECT m.qty INTO v_lama
  FROM public.barang_masuk m
  WHERE m.id_supplier = p_id_supplier
    AND m.id_barang = v_kode
    AND (
      (v_buku IS NOT NULL AND m.id_setoran_buku = v_buku)
      OR (v_buku IS NULL AND m.id_setoran_buku IS NULL AND m.tanggal = v_tgl)
    )
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Baris barang masuk tidak ada.';
  END IF;

  v_nilai := round(v_qty * v_harga)::integer;
  PERFORM public.barang_masuk_geser_stok(v_kode, v_qty - v_lama);
  PERFORM public.barang_masuk_terapkan_harga(p_id_supplier, v_kode, v_harga);

  UPDATE public.barang_masuk m
  SET qty = v_qty, nilai = v_nilai
  WHERE m.id_supplier = p_id_supplier
    AND m.id_barang = v_kode
    AND (
      (v_buku IS NOT NULL AND m.id_setoran_buku = v_buku)
      OR (v_buku IS NULL AND m.id_setoran_buku IS NULL AND m.tanggal = v_tgl)
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_barang_masuk_hapus(
  p_id_supplier integer,
  p_id_barang text
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
  v_tgl date;
  v_kode text;
  v_lama numeric(14, 4);
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya admin yang boleh menghapus barang masuk.';
  END IF;
  v_kode := nullif(btrim(COALESCE(p_id_barang, '')), '');
  IF COALESCE(p_id_supplier, 0) < 1 OR v_kode IS NULL THEN
    RAISE EXCEPTION 'SKU kosong.';
  END IF;

  PERFORM pg_advisory_xact_lock(88221020);
  SELECT o_buku, o_tgl INTO v_buku, v_tgl FROM public.barang_masuk_lingkup();

  SELECT m.qty INTO v_lama
  FROM public.barang_masuk m
  WHERE m.id_supplier = p_id_supplier
    AND m.id_barang = v_kode
    AND (
      (v_buku IS NOT NULL AND m.id_setoran_buku = v_buku)
      OR (v_buku IS NULL AND m.id_setoran_buku IS NULL AND m.tanggal = v_tgl)
    )
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Baris barang masuk tidak ada.';
  END IF;

  PERFORM public.barang_masuk_geser_stok(v_kode, -v_lama);
  DELETE FROM public.barang_masuk m
  WHERE m.id_supplier = p_id_supplier
    AND m.id_barang = v_kode
    AND (
      (v_buku IS NOT NULL AND m.id_setoran_buku = v_buku)
      OR (v_buku IS NULL AND m.id_setoran_buku IS NULL AND m.tanggal = v_tgl)
    );
END;
$$;

REVOKE ALL ON FUNCTION public.jual_dari_modal(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.jual_dari_modal(integer)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.barang_id_berikut() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.barang_id_berikut()
  TO postgres, service_role;
REVOKE ALL ON FUNCTION public.barang_masuk_lingkup() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.barang_masuk_lingkup()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.barang_masuk_geser_stok(text, numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.barang_masuk_geser_stok(text, numeric)
  TO postgres, service_role;
REVOKE ALL ON FUNCTION public.barang_masuk_terapkan_harga(integer, text, numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.barang_masuk_terapkan_harga(integer, text, numeric)
  TO postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_supplier_daftar() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_supplier_daftar()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_supplier_tambah(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_supplier_tambah(text)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_barang_cari(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_barang_cari(text)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_barang_masuk_ringkas() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_barang_masuk_ringkas()
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_barang_masuk_lihat(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_barang_masuk_lihat(integer)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_ongkir_lihat_supplier(integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_ongkir_lihat_supplier(integer)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_ongkir_simpan(integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_ongkir_simpan(integer, integer)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_barang_masuk_simpan(integer, jsonb, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_barang_masuk_simpan(integer, jsonb, integer)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_barang_masuk_ubah(integer, text, numeric, numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_barang_masuk_ubah(integer, text, numeric, numeric)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_barang_masuk_hapus(integer, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_barang_masuk_hapus(integer, text)
  TO authenticated, postgres, service_role;

NOTIFY pgrst, 'reload schema';
