-- Pengirim tahap 3: kunjungan toko. Jalankan SETELAH 025_pengirim.sql. Boleh diulang.

CREATE TABLE IF NOT EXISTS public.kunjungan_pengirim (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES public.pelanggan (id_pelanggan),
  rute_pengirim text NOT NULL,
  rute_sales text NOT NULL,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  jarak double precision NOT NULL DEFAULT 0,
  CONSTRAINT kunjungan_pengirim_rute_chk CHECK (
    btrim(rute_pengirim) <> '' AND btrim(rute_sales) <> ''
  ),
  CONSTRAINT kunjungan_pengirim_jarak_chk CHECK (jarak >= 0)
);

COMMENT ON TABLE public.kunjungan_pengirim IS
  'Check-in/out toko. Satu toko, satu hari Jakarta, satu grup pengirim (SBGP tanpa D/H).';
COMMENT ON COLUMN public.kunjungan_pengirim.rute_pengirim IS
  'Grup mobil (SBGP04), bukan akun SBGP04D / SBGP04H.';

CREATE UNIQUE INDEX IF NOT EXISTS kunjungan_pengirim_toko_hari_uidx
  ON public.kunjungan_pengirim (rute_pengirim, id_pelanggan, tanggal);
CREATE INDEX IF NOT EXISTS kunjungan_pengirim_tanggal_idx
  ON public.kunjungan_pengirim (rute_pengirim, tanggal DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.kunjungan_pengirim
  TO postgres, service_role;
GRANT SELECT ON TABLE public.kunjungan_pengirim TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.kunjungan_pengirim FROM authenticated;
REVOKE ALL ON TABLE public.kunjungan_pengirim FROM anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;

ALTER TABLE public.kunjungan_pengirim ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kunjungan_pengirim FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS kunjungan_pengirim_select ON public.kunjungan_pengirim;
CREATE POLICY kunjungan_pengirim_select
  ON public.kunjungan_pengirim
  FOR SELECT
  TO authenticated
  USING (
    public.pengirim_sedang_login()
    AND rute_pengirim = public.pengirim_grup_rute(public.pengirim_rute_saya())
  );

DROP FUNCTION IF EXISTS public.pengirim_kartu_toko(date);

CREATE OR REPLACE FUNCTION public.pengirim_kartu_toko(p_tanggal date)
RETURNS TABLE (
  id_pelanggan text,
  nama_pelanggan text,
  rute_sales text,
  latitude double precision,
  longitude double precision,
  jumlah_nota integer,
  omset_order bigint,
  omset_packed bigint,
  omset_actual bigint,
  omset_batal bigint,
  wajib_kunci integer,
  ada_dikirim boolean,
  ada_pending boolean,
  ada_batal boolean,
  ada_terkirim boolean,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_sales text[];
  v_hari date;
  v_today date;
  v_id_buku bigint;
  v_id_buka bigint;
  v_tgl_buka date;
  v_grup text;
BEGIN
  IF NOT public.pengirim_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  IF p_tanggal IS NULL THEN
    RAISE EXCEPTION 'Tanggal kosong';
  END IF;

  v_sales := public.pengirim_rute_sales();
  v_hari := p_tanggal;
  v_today := (timezone('Asia/Jakarta', clock_timestamp()))::date;
  v_grup := public.pengirim_grup_rute(public.pengirim_rute_saya());
  IF cardinality(v_sales) IS NULL OR cardinality(v_sales) = 0 THEN
    RETURN;
  END IF;

  SELECT b.id, b.tanggal INTO v_id_buka, v_tgl_buka
  FROM public.setoran_buku b
  WHERE NOT b.ditutup
  LIMIT 1;
  IF v_id_buka IS NOT NULL AND (v_hari = v_today OR v_hari = v_tgl_buka) THEN
    v_id_buku := v_id_buka;
  ELSE
    SELECT b.id INTO v_id_buku
    FROM public.setoran_buku b
    WHERE b.tanggal = v_hari
    ORDER BY b.id DESC
    LIMIT 1;
  END IF;

  RETURN QUERY
  WITH nota AS (
    SELECT t.*
    FROM public.transaksi t
    WHERE t.rute = ANY (v_sales)
      AND t.waktu_packed IS NOT NULL
      AND (
        (t.status = 'dikirim' AND v_hari = v_today)
        OR (
          t.status IN ('terkirim', 'batal')
          AND t.waktu_actual IS NOT NULL
          AND CASE
            WHEN v_id_buku IS NOT NULL THEN t.id_setoran_buku = v_id_buku
            ELSE (t.waktu_actual AT TIME ZONE 'Asia/Jakarta')::date = v_hari
          END
        )
      )
  ),
  hitung AS (
    SELECT
      n.id_pelanggan,
      max(n.nama_pelanggan) AS nama_pelanggan,
      max(n.rute) AS rute_sales,
      count(*)::integer AS jumlah_nota,
      coalesce(sum((
        SELECT coalesce(sum(i.subtotal_jual_order), 0)
        FROM public.transaksi_items i
        WHERE i.id_transaksi = n.id_transaksi
      )), 0)::bigint AS omset_order,
      coalesce(sum((
        SELECT coalesce(sum(i.subtotal_jual_packed), 0)
        FROM public.transaksi_items i
        WHERE i.id_transaksi = n.id_transaksi
      )), 0)::bigint AS omset_packed,
      coalesce(sum(
        CASE WHEN n.status = 'batal' THEN 0
             ELSE (
               SELECT coalesce(sum(i.subtotal_jual_actual), 0)
               FROM public.transaksi_items i
               WHERE i.id_transaksi = n.id_transaksi
             )
        END
      ), 0)::bigint AS omset_actual,
      coalesce(sum(
        CASE WHEN n.status = 'batal' THEN (
          SELECT coalesce(sum(i.subtotal_jual_packed), 0)
          FROM public.transaksi_items i
          WHERE i.id_transaksi = n.id_transaksi
        ) ELSE 0 END
      ), 0)::bigint AS omset_batal,
      count(*) FILTER (
        WHERE n.status = 'dikirim' AND NOT n.pending
      )::integer AS wajib_kunci,
      bool_or(n.status = 'dikirim') AS ada_dikirim,
      bool_or(n.pending) AS ada_pending,
      bool_or(n.status = 'batal') AS ada_batal,
      bool_or(n.status = 'terkirim') AS ada_terkirim
    FROM nota n
    GROUP BY n.id_pelanggan
  )
  SELECT
    h.id_pelanggan,
    h.nama_pelanggan,
    h.rute_sales,
    pl.latitude,
    pl.longitude,
    h.jumlah_nota,
    h.omset_order,
    h.omset_packed,
    h.omset_actual,
    h.omset_batal,
    h.wajib_kunci,
    h.ada_dikirim,
    h.ada_pending,
    h.ada_batal,
    h.ada_terkirim,
    k.waktu_masuk,
    k.waktu_keluar
  FROM hitung h
  LEFT JOIN public.pelanggan pl ON pl.id_pelanggan = h.id_pelanggan
  LEFT JOIN public.kunjungan_pengirim k
    ON k.id_pelanggan = h.id_pelanggan
   AND k.rute_pengirim = v_grup
   AND k.tanggal = v_hari
  ORDER BY lower(h.nama_pelanggan), h.id_pelanggan;
END;
$$;

CREATE OR REPLACE FUNCTION public.pengirim_nota_toko(
  p_tanggal date,
  p_id_pelanggan text
)
RETURNS TABLE (
  id_transaksi text,
  status text,
  pending boolean,
  waktu_order timestamptz,
  waktu_packed timestamptz,
  waktu_actual timestamptz,
  omset_order bigint,
  omset_packed bigint,
  omset_actual bigint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_sales text[];
  v_hari date;
  v_today date;
  v_id text;
  v_id_buku bigint;
  v_id_buka bigint;
  v_tgl_buka date;
BEGIN
  IF NOT public.pengirim_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  v_id := btrim(COALESCE(p_id_pelanggan, ''));
  IF p_tanggal IS NULL OR v_id = '' THEN
    RAISE EXCEPTION 'Tanggal dan toko wajib.';
  END IF;
  v_sales := public.pengirim_rute_sales();
  v_hari := p_tanggal;
  v_today := (timezone('Asia/Jakarta', clock_timestamp()))::date;

  SELECT b.id, b.tanggal INTO v_id_buka, v_tgl_buka
  FROM public.setoran_buku b
  WHERE NOT b.ditutup
  LIMIT 1;
  IF v_id_buka IS NOT NULL AND (v_hari = v_today OR v_hari = v_tgl_buka) THEN
    v_id_buku := v_id_buka;
  ELSE
    SELECT b.id INTO v_id_buku
    FROM public.setoran_buku b
    WHERE b.tanggal = v_hari
    ORDER BY b.id DESC
    LIMIT 1;
  END IF;

  RETURN QUERY
  SELECT
    t.id_transaksi,
    t.status,
    t.pending,
    t.waktu_order,
    t.waktu_packed,
    t.waktu_actual,
    coalesce(sum(i.subtotal_jual_order), 0)::bigint,
    coalesce(sum(i.subtotal_jual_packed), 0)::bigint,
    coalesce(sum(i.subtotal_jual_actual), 0)::bigint
  FROM public.transaksi t
  LEFT JOIN public.transaksi_items i ON i.id_transaksi = t.id_transaksi
  WHERE t.rute = ANY (v_sales)
    AND t.id_pelanggan = v_id
    AND t.waktu_packed IS NOT NULL
    AND (
      (t.status = 'dikirim' AND v_hari = v_today)
      OR (
        t.status IN ('terkirim', 'batal')
        AND t.waktu_actual IS NOT NULL
        AND CASE
          WHEN v_id_buku IS NOT NULL THEN t.id_setoran_buku = v_id_buku
          ELSE (t.waktu_actual AT TIME ZONE 'Asia/Jakarta')::date = v_hari
        END
      )
    )
  GROUP BY
    t.id_transaksi, t.status, t.pending, t.waktu_order, t.waktu_packed, t.waktu_actual
  ORDER BY t.waktu_order;
END;
$$;

DROP FUNCTION IF EXISTS public.pengirim_scan_kunjungan(text, boolean, double precision, double precision);
DROP FUNCTION IF EXISTS public.pengirim_scan_kunjungan(text, boolean, double precision, double precision, timestamptz);

CREATE OR REPLACE FUNCTION public.pengirim_scan_kunjungan(
  p_id_pelanggan text,
  p_keluar boolean,
  p_latitude double precision,
  p_longitude double precision,
  p_waktu timestamptz
)
RETURNS timestamptz
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id text;
  v_rute_p text;
  v_rute_s text;
  v_sales text[];
  v_lat double precision;
  v_lng double precision;
  v_jarak double precision;
  v_tanggal date;
  v_masuk timestamptz;
  v_keluar timestamptz;
  v_now timestamptz;
BEGIN
  IF NOT public.pengirim_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  IF public.pengirim_id_absensi_saya() IS NULL THEN
    RAISE EXCEPTION 'Belum scan masuk gudang.';
  END IF;

  IF p_waktu IS NULL THEN
    RAISE EXCEPTION 'Waktu HP kosong';
  END IF;
  IF abs(extract(epoch FROM (p_waktu - clock_timestamp()))) > 180 THEN
    RAISE EXCEPTION 'Jam HP tidak sesuai waktu Jakarta. Nyalakan waktu otomatis, lalu scan lagi.';
  END IF;
  v_now := p_waktu;

  v_id := btrim(COALESCE(p_id_pelanggan, ''));
  v_rute_p := public.pengirim_grup_rute(public.pengirim_rute_saya());
  v_sales := public.pengirim_rute_sales();
  IF v_id = '' OR v_rute_p IS NULL OR v_rute_p = '' THEN
    RAISE EXCEPTION 'Toko atau rute kosong.';
  END IF;
  IF p_latitude IS NULL OR p_longitude IS NULL THEN
    RAISE EXCEPTION 'Koordinat HP kosong';
  END IF;

  SELECT pl.latitude, pl.longitude, pl.rute
  INTO v_lat, v_lng, v_rute_s
  FROM public.pelanggan pl
  WHERE pl.id_pelanggan = v_id
    AND pl.rute = ANY (v_sales)
    AND COALESCE(pl.aktif, true);

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Toko tidak ada di rute Anda';
  END IF;
  IF v_lat IS NULL OR v_lng IS NULL OR (v_lat = 0 AND v_lng = 0) THEN
    RAISE EXCEPTION 'Toko belum punya koordinat GPS.';
  END IF;

  v_jarak := 6371000 * 2 * asin(sqrt(least(1.0,
    power(sin(radians(p_latitude - v_lat) / 2), 2) +
    cos(radians(v_lat)) * cos(radians(p_latitude)) *
    power(sin(radians(p_longitude - v_lng) / 2), 2)
  )));

  IF v_jarak > 20 THEN
    RAISE EXCEPTION 'Anda masih % m dari toko. Mendekatlah, lalu scan lagi.',
      round(v_jarak);
  END IF;

  v_tanggal := (v_now AT TIME ZONE 'Asia/Jakarta')::date;
  PERFORM pg_advisory_xact_lock(hashtext(v_rute_p || ':' || v_id || ':' || v_tanggal::text));

  SELECT waktu_masuk, waktu_keluar
  INTO v_masuk, v_keluar
  FROM public.kunjungan_pengirim
  WHERE rute_pengirim = v_rute_p
    AND id_pelanggan = v_id
    AND tanggal = v_tanggal
  FOR UPDATE;

  IF COALESCE(p_keluar, false) THEN
    IF v_masuk IS NULL THEN
      RAISE EXCEPTION 'Belum check-in hari ini. Scan masuk dulu.';
    END IF;
    IF v_keluar IS NOT NULL THEN
      RETURN v_keluar;
    END IF;
    UPDATE public.kunjungan_pengirim
    SET waktu_keluar = v_now,
        jarak = v_jarak
    WHERE rute_pengirim = v_rute_p
      AND id_pelanggan = v_id
      AND tanggal = v_tanggal;
    RETURN v_now;
  END IF;

  IF v_keluar IS NOT NULL THEN
    RAISE EXCEPTION 'Kunjungan toko ini hari ini sudah selesai.';
  END IF;
  IF v_masuk IS NOT NULL THEN
    RETURN v_masuk;
  END IF;

  INSERT INTO public.kunjungan_pengirim (
    id_pelanggan, rute_pengirim, rute_sales, tanggal, waktu_masuk, waktu_keluar, jarak
  ) VALUES (
    v_id, v_rute_p, v_rute_s, v_tanggal, v_now, NULL, v_jarak
  )
  ON CONFLICT (rute_pengirim, id_pelanggan, tanggal) DO UPDATE
  SET waktu_masuk = COALESCE(public.kunjungan_pengirim.waktu_masuk, EXCLUDED.waktu_masuk),
      jarak = EXCLUDED.jarak
  WHERE public.kunjungan_pengirim.waktu_keluar IS NULL;

  RETURN v_now;
END;
$$;

REVOKE ALL ON FUNCTION public.pengirim_kartu_toko(date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_kartu_toko(date)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.pengirim_nota_toko(date, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_nota_toko(date, text)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.pengirim_scan_kunjungan(text, boolean, double precision, double precision, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_scan_kunjungan(text, boolean, double precision, double precision, timestamptz)
  TO authenticated, postgres, service_role;

NOTIFY pgrst, 'reload schema';
