-- Setoran pengirim: uang yang diisi pengirim, satu baris per mobil per buku.
-- Omset/retur tidak disimpan di sini (dihitung dari transaksi / retur).
-- Jalankan SETELAH 028. Boleh diulang.

CREATE TABLE IF NOT EXISTS public.setoran_pengirim (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rute_pengirim text NOT NULL,
  id_setoran_buku bigint NOT NULL REFERENCES public.setoran_buku (id),
  jumlah_transfer integer NOT NULL DEFAULT 0,
  jumlah_tunai integer NOT NULL DEFAULT 0,
  jumlah_bop integer NOT NULL DEFAULT 0,
  kasbon_supir integer NOT NULL DEFAULT 0,
  kasbon_kenek integer NOT NULL DEFAULT 0,
  waktu_setor timestamptz NOT NULL DEFAULT clock_timestamp(),
  dicatat_oleh text NOT NULL DEFAULT '',
  dicatat_rute text NOT NULL DEFAULT '',
  CONSTRAINT setoran_pengirim_rute_chk CHECK (btrim(rute_pengirim) <> ''),
  CONSTRAINT setoran_pengirim_uang_chk CHECK (
    jumlah_transfer >= 0
    AND jumlah_tunai >= 0
    AND jumlah_bop >= 0
    AND jumlah_bop <= 170000
    AND kasbon_supir >= 0
    AND kasbon_kenek >= 0
  )
);

COMMENT ON TABLE public.setoran_pengirim IS
  'Satu setoran per grup pengirim per buku. Hanya uang setor + kasbon + siapa.';
COMMENT ON COLUMN public.setoran_pengirim.rute_pengirim IS
  'Grup mobil (SBGP04). Bukan akun D/H.';
COMMENT ON COLUMN public.setoran_pengirim.id_setoran_buku IS
  'Buku terbuka saat pengirim menekan Setor.';
COMMENT ON COLUMN public.setoran_pengirim.dicatat_oleh IS
  'Nama akun yang menekan Setor.';
COMMENT ON COLUMN public.setoran_pengirim.dicatat_rute IS
  'Akun D/H yang menekan Setor (SBGP04D).';

CREATE UNIQUE INDEX IF NOT EXISTS setoran_pengirim_rute_buku_uidx
  ON public.setoran_pengirim (rute_pengirim, id_setoran_buku);
CREATE INDEX IF NOT EXISTS setoran_pengirim_buku_idx
  ON public.setoran_pengirim (id_setoran_buku);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.setoran_pengirim
  TO postgres, service_role;
GRANT SELECT ON TABLE public.setoran_pengirim TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.setoran_pengirim FROM authenticated;
REVOKE ALL ON TABLE public.setoran_pengirim FROM anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;

ALTER TABLE public.setoran_pengirim ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.setoran_pengirim FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS setoran_pengirim_select ON public.setoran_pengirim;
CREATE POLICY setoran_pengirim_select
  ON public.setoran_pengirim
  FOR SELECT
  TO authenticated
  USING (
    public.admin_sedang_login()
    OR (
      public.pengirim_sedang_login()
      AND rute_pengirim = public.pengirim_grup_rute(public.pengirim_rute_saya())
    )
  );

CREATE OR REPLACE FUNCTION public.setoran_pengirim_cap_buku()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.id_setoran_buku IS NOT NULL THEN
    NEW.id_setoran_buku := OLD.id_setoran_buku;
    NEW.rute_pengirim := public.pengirim_grup_rute(OLD.rute_pengirim);
    RETURN NEW;
  END IF;

  SELECT b.id INTO v_id
  FROM public.setoran_buku b
  WHERE NOT b.ditutup
  LIMIT 1;
  IF v_id IS NULL THEN
    RAISE EXCEPTION 'Tidak ada buku setoran terbuka. Setoran tidak dicatat ke tanggal berikutnya.';
  END IF;
  NEW.id_setoran_buku := v_id;
  NEW.rute_pengirim := public.pengirim_grup_rute(NEW.rute_pengirim);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS setoran_pengirim_cap_buku_trg ON public.setoran_pengirim;
CREATE TRIGGER setoran_pengirim_cap_buku_trg
  BEFORE INSERT OR UPDATE OF id_setoran_buku, rute_pengirim
  ON public.setoran_pengirim
  FOR EACH ROW
  EXECUTE FUNCTION public.setoran_pengirim_cap_buku();

REVOKE ALL ON FUNCTION public.setoran_pengirim_cap_buku() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.setoran_pengirim_cap_buku()
  TO postgres, service_role;

NOTIFY pgrst, 'reload schema';
