-- Klaim retur pengirim per toko per buku. Stok langsung seperti batal
-- (stok_kembali_packing). Tidak menunggu cek fisik admin.
-- Jalankan SETELAH 038 dan 039. Boleh diulang.

CREATE TABLE IF NOT EXISTS public.retur_toko (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES public.setoran_buku (id),
  tanggal date NOT NULL,
  rute_pengirim text NOT NULL,
  id_pelanggan text NOT NULL,
  kode_barang text NOT NULL,
  nama_barang text NOT NULL DEFAULT '',
  qty integer NOT NULL,
  harga_jual integer NOT NULL DEFAULT 0,
  waktu_catat timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT retur_toko_qty_chk CHECK (qty > 0),
  CONSTRAINT retur_toko_harga_chk CHECK (harga_jual >= 0),
  CONSTRAINT retur_toko_rute_chk CHECK (btrim(rute_pengirim) <> ''),
  CONSTRAINT retur_toko_toko_chk CHECK (btrim(id_pelanggan) <> ''),
  CONSTRAINT retur_toko_sku_chk CHECK (btrim(kode_barang) <> '')
);

COMMENT ON TABLE public.retur_toko IS
  'Klaim retur pengirim. Bukan tebus nota. Stok geser saat simpan, seperti batal.';

CREATE UNIQUE INDEX IF NOT EXISTS retur_toko_buku_uidx
  ON public.retur_toko (id_setoran_buku, rute_pengirim, id_pelanggan, kode_barang);
CREATE INDEX IF NOT EXISTS retur_toko_buku_idx
  ON public.retur_toko (id_setoran_buku);
CREATE INDEX IF NOT EXISTS retur_toko_rute_idx
  ON public.retur_toko (rute_pengirim, tanggal);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.retur_toko
  TO postgres, service_role;
GRANT SELECT ON TABLE public.retur_toko TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.retur_toko FROM authenticated;
REVOKE ALL ON TABLE public.retur_toko FROM anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;

ALTER TABLE public.retur_toko ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.retur_toko FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS retur_toko_select ON public.retur_toko;
CREATE POLICY retur_toko_select
  ON public.retur_toko
  FOR SELECT
  TO authenticated
  USING (
    public.admin_sedang_login()
    OR (
      public.pengirim_sedang_login()
      AND rute_pengirim = public.pengirim_grup_rute(public.pengirim_rute_saya())
    )
  );

CREATE OR REPLACE FUNCTION public.retur_toko_cap_buku()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
  v_tgl date;
BEGIN
  IF TG_OP = 'UPDATE' AND OLD.id_setoran_buku IS NOT NULL THEN
    NEW.id_setoran_buku := OLD.id_setoran_buku;
    NEW.rute_pengirim := public.pengirim_grup_rute(OLD.rute_pengirim);
    SELECT b.tanggal INTO v_tgl
    FROM public.setoran_buku b
    WHERE b.id = OLD.id_setoran_buku;
    IF v_tgl IS NOT NULL THEN
      NEW.tanggal := v_tgl;
    END IF;
    RETURN NEW;
  END IF;

  SELECT b.id, b.tanggal INTO v_id, v_tgl
  FROM public.setoran_buku b
  WHERE NOT b.ditutup
  LIMIT 1;
  IF v_id IS NULL THEN
    RAISE EXCEPTION 'Tidak ada buku setoran terbuka. Retur tidak dicatat ke tanggal berikutnya.';
  END IF;
  NEW.id_setoran_buku := v_id;
  NEW.tanggal := v_tgl;
  NEW.rute_pengirim := public.pengirim_grup_rute(NEW.rute_pengirim);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS retur_toko_cap_buku_trg ON public.retur_toko;
CREATE TRIGGER retur_toko_cap_buku_trg
  BEFORE INSERT OR UPDATE OF id_setoran_buku, rute_pengirim, tanggal
  ON public.retur_toko
  FOR EACH ROW
  EXECUTE FUNCTION public.retur_toko_cap_buku();

REVOKE ALL ON FUNCTION public.retur_toko_cap_buku() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.retur_toko_cap_buku()
  TO postgres, service_role;

-- Balikkan stok_kembali_packing (batal/retur dibatalkan).
CREATE OR REPLACE FUNCTION public.stok_balik_dari_packing(
  p_id_barang text,
  p_qty numeric
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_buku bigint;
  v_qty numeric(14, 4);
  v_fisik numeric(14, 4);
BEGIN
  v_qty := round(GREATEST(COALESCE(p_qty, 0), 0), 4);
  IF v_qty = 0 OR btrim(COALESCE(p_id_barang, '')) = '' THEN
    RETURN;
  END IF;

  v_buku := public.setoran_buku_terbuka();
  IF v_buku IS NULL THEN
    PERFORM set_config('obos.boleh_tulis_stok', 'on', true);
    UPDATE public.barang
    SET stok = GREATEST(COALESCE(stok, 0) - v_qty, 0)
    WHERE id_barang = p_id_barang;
    RETURN;
  END IF;

  SELECT so.stok_fisik INTO v_fisik
  FROM public.stok_opname so
  WHERE so.id_setoran_buku = v_buku
    AND so.id_barang = p_id_barang
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  UPDATE public.stok_opname
  SET
    qty_packed = qty_packed + v_qty,
    stok_fisik = CASE
      WHEN stok_fisik IS NULL THEN NULL
      ELSE GREATEST(stok_fisik - v_qty, 0)
    END
  WHERE id_setoran_buku = v_buku
    AND id_barang = p_id_barang;
END;
$$;

REVOKE ALL ON FUNCTION public.stok_balik_dari_packing(text, numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.stok_balik_dari_packing(text, numeric)
  TO postgres, service_role;

CREATE OR REPLACE FUNCTION public.pengirim_buku_hari(p_tanggal date)
RETURNS bigint
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_hari date;
  v_today date;
  v_id bigint;
  v_tgl date;
BEGIN
  v_hari := p_tanggal;
  v_today := (timezone('Asia/Jakarta', clock_timestamp()))::date;
  SELECT b.id, b.tanggal INTO v_id, v_tgl
  FROM public.setoran_buku b
  WHERE NOT b.ditutup
  LIMIT 1;
  IF v_id IS NOT NULL AND (v_hari = v_today OR v_hari = v_tgl) THEN
    RETURN v_id;
  END IF;
  SELECT b.id INTO v_id
  FROM public.setoran_buku b
  WHERE b.tanggal = v_hari
  ORDER BY b.id DESC
  LIMIT 1;
  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.pengirim_buku_hari(date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_buku_hari(date)
  TO authenticated, postgres, service_role;

CREATE OR REPLACE FUNCTION public.pengirim_barang_cari(p_cari text)
RETURNS TABLE (
  kode_barang text,
  nama_barang text,
  harga_jual integer
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_q text;
BEGIN
  IF NOT public.pengirim_sedang_login() THEN
    RETURN;
  END IF;
  v_q := btrim(COALESCE(p_cari, ''));
  IF char_length(v_q) < 2 THEN
    RETURN;
  END IF;
  v_q := '%' || replace(replace(v_q, '%', ''), '_', '') || '%';
  RETURN QUERY
  SELECT
    b.id_barang,
    COALESCE(NULLIF(btrim(b.nama_barang), ''), b.id_barang),
    COALESCE(b.harga_jual, 0)::integer
  FROM public.barang b
  WHERE b.id_barang ILIKE v_q OR b.nama_barang ILIKE v_q
  ORDER BY b.nama_barang
  LIMIT 30;
END;
$$;

CREATE OR REPLACE FUNCTION public.pengirim_retur_dikunci(p_tanggal date)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_rute text;
  v_buku bigint;
BEGIN
  IF NOT public.pengirim_sedang_login() OR p_tanggal IS NULL THEN
    RETURN true;
  END IF;
  v_rute := public.pengirim_grup_rute(public.pengirim_rute_saya());
  v_buku := public.pengirim_buku_hari(p_tanggal);
  IF v_rute IS NULL OR v_buku IS NULL THEN
    RETURN true;
  END IF;
  RETURN EXISTS (
    SELECT 1 FROM public.setoran_pengirim s
    WHERE s.rute_pengirim = v_rute
      AND s.id_setoran_buku = v_buku
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.pengirim_retur_toko_lihat(
  p_tanggal date,
  p_id_pelanggan text
)
RETURNS TABLE (
  kode_barang text,
  nama_barang text,
  qty integer,
  harga_jual integer,
  nilai integer,
  dikunci boolean
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_rute text;
  v_id text;
  v_buku bigint;
  v_kunci boolean;
BEGIN
  IF NOT public.pengirim_sedang_login() OR p_tanggal IS NULL THEN
    RETURN;
  END IF;
  v_rute := public.pengirim_grup_rute(public.pengirim_rute_saya());
  v_id := nullif(btrim(COALESCE(p_id_pelanggan, '')), '');
  v_buku := public.pengirim_buku_hari(p_tanggal);
  IF v_rute IS NULL OR v_id IS NULL OR v_buku IS NULL THEN
    RETURN;
  END IF;
  v_kunci := public.pengirim_retur_dikunci(p_tanggal);
  RETURN QUERY
  SELECT
    i.kode_barang,
    COALESCE(NULLIF(btrim(i.nama_barang), ''), i.kode_barang),
    i.qty,
    i.harga_jual,
    (i.qty * i.harga_jual)::integer,
    v_kunci
  FROM public.retur_toko i
  WHERE i.id_setoran_buku = v_buku
    AND i.rute_pengirim = v_rute
    AND i.id_pelanggan = v_id
  ORDER BY 2;
END;
$$;

CREATE OR REPLACE FUNCTION public.pengirim_retur_rute_lihat(p_tanggal date)
RETURNS TABLE (
  id_pelanggan text,
  nama_toko text,
  kode_barang text,
  nama_barang text,
  qty integer,
  nilai integer
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_rute text;
  v_buku bigint;
BEGIN
  IF NOT public.pengirim_sedang_login() OR p_tanggal IS NULL THEN
    RETURN;
  END IF;
  v_rute := public.pengirim_grup_rute(public.pengirim_rute_saya());
  v_buku := public.pengirim_buku_hari(p_tanggal);
  IF v_rute IS NULL OR v_buku IS NULL THEN
    RETURN;
  END IF;
  RETURN QUERY
  SELECT
    i.id_pelanggan,
    COALESCE(NULLIF(btrim(p.nama_pelanggan), ''), i.id_pelanggan),
    i.kode_barang,
    COALESCE(NULLIF(btrim(i.nama_barang), ''), i.kode_barang),
    i.qty,
    (i.qty * i.harga_jual)::integer
  FROM public.retur_toko i
  LEFT JOIN public.pelanggan p ON p.id_pelanggan = i.id_pelanggan
  WHERE i.id_setoran_buku = v_buku
    AND i.rute_pengirim = v_rute
  ORDER BY 2, 4;
END;
$$;

CREATE OR REPLACE FUNCTION public.pengirim_retur_toko_simpan(
  p_tanggal date,
  p_id_pelanggan text,
  p_baris jsonb
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_rute text;
  v_id text;
  v_hari date;
  v_buku bigint;
  r jsonb;
  v_kode text;
  v_nama text;
  v_qty integer;
  v_harga integer;
  rec record;
BEGIN
  IF NOT public.pengirim_sedang_login() OR p_tanggal IS NULL THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  IF public.pengirim_id_absensi_saya() IS NULL THEN
    RAISE EXCEPTION 'Belum scan masuk.';
  END IF;
  v_hari := (timezone('Asia/Jakarta', clock_timestamp()))::date;
  IF p_tanggal <> v_hari THEN
    RAISE EXCEPTION 'Retur hanya bisa dicatat untuk hari ini.';
  END IF;
  v_rute := public.pengirim_grup_rute(public.pengirim_rute_saya());
  v_id := nullif(btrim(COALESCE(p_id_pelanggan, '')), '');
  IF v_rute IS NULL OR v_id IS NULL THEN
    RETURN false;
  END IF;
  v_buku := public.setoran_buku_terbuka();
  IF v_buku IS NULL THEN
    RAISE EXCEPTION 'Tidak ada buku setoran terbuka. Retur tidak dicatat ke tanggal berikutnya.';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtext(v_rute), hashtext(v_buku::text));

  IF NOT EXISTS (
    SELECT 1 FROM public.kunjungan_pengirim k
    WHERE k.tanggal = p_tanggal
      AND k.id_pelanggan = v_id
      AND k.waktu_masuk IS NOT NULL
      AND public.pengirim_grup_rute(k.rute_pengirim) = v_rute
  ) THEN
    RAISE EXCEPTION 'Check-in toko dulu sebelum mencatat retur.';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.setoran_pengirim s
    WHERE s.rute_pengirim = v_rute
      AND s.id_setoran_buku = v_buku
  ) THEN
    RAISE EXCEPTION 'Setoran sudah dicatat. Retur tidak bisa diubah.';
  END IF;
  IF p_baris IS NULL OR jsonb_typeof(p_baris) <> 'array' THEN
    RETURN false;
  END IF;

  CREATE TEMP TABLE tmp_retur_baru (
    kode text PRIMARY KEY,
    nama text,
    qty integer,
    harga integer
  ) ON COMMIT DROP;

  FOR r IN SELECT value FROM jsonb_array_elements(p_baris)
  LOOP
    v_kode := nullif(btrim(COALESCE(r ->> 'kode_barang', '')), '');
    v_nama := btrim(COALESCE(r ->> 'nama_barang', ''));
    BEGIN
      v_qty := GREATEST(COALESCE((r ->> 'qty')::integer, 0), 0);
    EXCEPTION WHEN OTHERS THEN
      CONTINUE;
    END;
    BEGIN
      v_harga := GREATEST(COALESCE((r ->> 'harga_jual')::integer, 0), 0);
    EXCEPTION WHEN OTHERS THEN
      v_harga := 0;
    END;
    IF v_kode IS NULL OR v_qty <= 0 THEN
      CONTINUE;
    END IF;
    IF v_nama = '' OR v_harga <= 0 THEN
      SELECT
        CASE WHEN v_nama = '' THEN COALESCE(NULLIF(btrim(b.nama_barang), ''), v_kode) ELSE v_nama END,
        CASE WHEN v_harga <= 0 THEN COALESCE(b.harga_jual, 0) ELSE v_harga END
      INTO v_nama, v_harga
      FROM public.barang b
      WHERE b.id_barang = v_kode;
      v_nama := COALESCE(v_nama, v_kode);
      v_harga := COALESCE(v_harga, 0);
    END IF;
    INSERT INTO tmp_retur_baru (kode, nama, qty, harga)
    VALUES (v_kode, v_nama, v_qty, v_harga)
    ON CONFLICT (kode) DO UPDATE SET
      qty = EXCLUDED.qty,
      nama = EXCLUDED.nama,
      harga = EXCLUDED.harga;
  END LOOP;

  FOR rec IN
    SELECT
      COALESCE(l.kode_barang, n.kode) AS kode,
      COALESCE(l.qty, 0) AS lama,
      COALESCE(n.qty, 0) AS baru
    FROM (
      SELECT kode_barang, qty
      FROM public.retur_toko
      WHERE id_setoran_buku = v_buku
        AND rute_pengirim = v_rute
        AND id_pelanggan = v_id
    ) l
    FULL JOIN tmp_retur_baru n ON n.kode = l.kode_barang
  LOOP
    IF rec.baru > rec.lama THEN
      PERFORM public.stok_kembali_packing(rec.kode, rec.baru - rec.lama);
    ELSIF rec.lama > rec.baru THEN
      PERFORM public.stok_balik_dari_packing(rec.kode, rec.lama - rec.baru);
    END IF;
  END LOOP;

  DELETE FROM public.retur_toko
  WHERE id_setoran_buku = v_buku
    AND rute_pengirim = v_rute
    AND id_pelanggan = v_id;

  INSERT INTO public.retur_toko (
    rute_pengirim, id_pelanggan, kode_barang, nama_barang, qty, harga_jual
  )
  SELECT v_rute, v_id, kode, nama, qty, harga
  FROM tmp_retur_baru;

  RETURN true;
END;
$$;

CREATE OR REPLACE FUNCTION public.pengirim_ringkas_hari(p_tanggal date)
RETURNS TABLE (
  jumlah_toko integer,
  jumlah_nota integer,
  wajib_kunci integer,
  omset_order bigint,
  omset_packed bigint,
  omset_actual bigint,
  omset_batal bigint,
  omset_pending bigint,
  omset_retur bigint,
  laba_order bigint,
  laba_packed bigint,
  laba_actual bigint
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_sales text[];
  v_hari date;
  v_today date;
  v_id_buku bigint;
  v_rute text;
  v_retur bigint := 0;
BEGIN
  IF NOT public.pengirim_sedang_login() THEN
    RAISE EXCEPTION 'Sesi login tidak aktif.';
  END IF;
  IF p_tanggal IS NULL THEN
    RAISE EXCEPTION 'Tanggal kosong';
  END IF;

  v_sales := public.pengirim_rute_sales();
  v_hari := p_tanggal;
  v_today := (timezone('Asia/Jakarta', clock_timestamp()))::date;
  v_rute := public.pengirim_grup_rute(public.pengirim_rute_saya());
  IF cardinality(v_sales) IS NULL OR cardinality(v_sales) = 0 THEN
    RETURN;
  END IF;

  v_id_buku := public.pengirim_buku_hari(v_hari);
  IF v_id_buku IS NOT NULL AND v_rute IS NOT NULL THEN
    SELECT coalesce(sum(i.qty * i.harga_jual), 0)::bigint
    INTO v_retur
    FROM public.retur_toko i
    WHERE i.id_setoran_buku = v_id_buku
      AND i.rute_pengirim = v_rute;
  END IF;

  RETURN QUERY
  WITH nota AS (
    SELECT t.*
    FROM public.transaksi t
    WHERE t.rute = ANY (v_sales)
      AND t.waktu_packed IS NOT NULL
      AND (
        (v_id_buku IS NOT NULL AND t.id_setoran_buku = v_id_buku)
        OR (
          t.status = 'dikirim'
          AND t.id_setoran_buku IS NULL
          AND v_hari = v_today
        )
        OR (
          v_id_buku IS NULL
          AND t.status IN ('terkirim', 'batal')
          AND t.waktu_actual IS NOT NULL
          AND (t.waktu_actual AT TIME ZONE 'Asia/Jakarta')::date = v_hari
        )
      )
  ),
  item AS (
    SELECT
      n.id_transaksi,
      n.id_pelanggan,
      n.status,
      n.pending,
      coalesce(sum(i.subtotal_jual_order), 0) AS jual_order,
      coalesce(sum(i.subtotal_beli_order), 0) AS beli_order,
      coalesce(sum(i.subtotal_jual_packed), 0) AS jual_packed,
      coalesce(sum(i.subtotal_beli_packed), 0) AS beli_packed,
      coalesce(sum(i.subtotal_jual_actual), 0) AS jual_actual,
      coalesce(sum(i.subtotal_beli_actual), 0) AS beli_actual
    FROM nota n
    JOIN public.v_transaksi_item i ON i.id_transaksi = n.id_transaksi
    GROUP BY n.id_transaksi, n.id_pelanggan, n.status, n.pending
  )
  SELECT
    count(DISTINCT i.id_pelanggan)::integer,
    count(*)::integer,
    count(*) FILTER (WHERE i.status = 'dikirim' AND NOT i.pending)::integer,
    coalesce(sum(i.jual_order), 0)::bigint,
    coalesce(sum(i.jual_packed), 0)::bigint,
    coalesce(sum(CASE WHEN i.status = 'batal' THEN 0 ELSE i.jual_actual END), 0)::bigint,
    coalesce(sum(CASE WHEN i.status = 'batal' THEN i.jual_packed ELSE 0 END), 0)::bigint,
    coalesce(sum(CASE WHEN i.pending THEN i.jual_packed ELSE 0 END), 0)::bigint,
    v_retur,
    coalesce(sum(i.jual_order - i.beli_order), 0)::bigint,
    coalesce(sum(i.jual_packed - i.beli_packed), 0)::bigint,
    coalesce(sum(
      CASE WHEN i.status = 'batal' THEN 0 ELSE i.jual_actual - i.beli_actual END
    ), 0)::bigint
  FROM item i;
END;
$$;

REVOKE ALL ON FUNCTION public.pengirim_barang_cari(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_barang_cari(text)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.pengirim_retur_dikunci(date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_retur_dikunci(date)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.pengirim_retur_toko_lihat(date, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_retur_toko_lihat(date, text)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.pengirim_retur_rute_lihat(date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_retur_rute_lihat(date)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.pengirim_retur_toko_simpan(date, text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_retur_toko_simpan(date, text, jsonb)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.pengirim_ringkas_hari(date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pengirim_ringkas_hari(date)
  TO authenticated, postgres, service_role;

NOTIFY pgrst, 'reload schema';
