-- Mutasi bank admin: unggah CSV, cocok ke rute, tampil di kartu.
-- Jalankan SETELAH 051. Boleh diulang.

CREATE TABLE IF NOT EXISTS public.mutasi_bank (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES public.setoran_buku (id),
  tanggal date NOT NULL,
  tanggal_mutasi date,
  rekening_alias text,
  jumlah integer NOT NULL DEFAULT 0,
  berita text,
  rute_pengirim text,
  status_cocok text NOT NULL DEFAULT 'tidak_cocok',
  nama_berkas text,
  dicatat_oleh text,
  waktu_unggah timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT mutasi_bank_status_chk
    CHECK (status_cocok IN ('cocok', 'manual', 'tidak_cocok')),
  CONSTRAINT mutasi_bank_jumlah_chk CHECK (jumlah >= 0)
);

COMMENT ON TABLE public.mutasi_bank IS
  'Baris mutasi bank yang diunggah admin untuk mencocokkan transfer setoran.';

CREATE INDEX IF NOT EXISTS mutasi_bank_buku_idx
  ON public.mutasi_bank (id_setoran_buku);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.mutasi_bank
  TO postgres, service_role;
GRANT SELECT ON TABLE public.mutasi_bank TO authenticated;
REVOKE INSERT, UPDATE, DELETE ON TABLE public.mutasi_bank FROM authenticated;
REVOKE ALL ON TABLE public.mutasi_bank FROM anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO postgres, service_role;

ALTER TABLE public.mutasi_bank ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mutasi_bank FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS mutasi_bank_select ON public.mutasi_bank;
CREATE POLICY mutasi_bank_select
  ON public.mutasi_bank
  FOR SELECT
  TO authenticated
  USING (public.admin_sedang_login());

CREATE OR REPLACE FUNCTION public._mutasi_buku_kartu()
RETURNS bigint
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
BEGIN
  v_id := public.setoran_buku_terbuka();
  IF v_id IS NOT NULL THEN
    RETURN v_id;
  END IF;
  SELECT b.id INTO v_id
  FROM public.setoran_buku b
  ORDER BY b.id DESC
  LIMIT 1;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_mutasi_tanggal_berita_wajib(p_judul date)
RETURNS date
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT CASE
    WHEN EXTRACT(ISODOW FROM (p_judul + 1))::integer = 7 THEN p_judul + 2
    ELSE p_judul + 1
  END;
$$;

CREATE OR REPLACE FUNCTION public.admin_mutasi_rute_dari_berita(
  p_berita text,
  p_tanggal date
)
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_teks text;
  v_n text;
  v_hari text;
  v_tgl date;
  v_wajib date;
BEGIN
  IF p_tanggal IS NULL THEN
    RETURN NULL;
  END IF;
  v_wajib := public.admin_mutasi_tanggal_berita_wajib(p_tanggal);
  v_teks := upper(btrim(COALESCE(p_berita, '')));
  v_n := substring(v_teks from 'SBGP\s*0*([1-4])');
  v_hari := substring(v_teks from 'SBGP\s*0*[1-4][^\d]*([0-9]{1,2}[/\-.][0-9]{1,2}[/\-.][0-9]{2,4})');
  IF v_n IS NULL THEN
    RETURN NULL;
  END IF;
  IF v_hari IS NULL THEN
    RETURN NULL;
  END IF;
  BEGIN
    IF v_hari ~ '^[0-9]{1,2}/[0-9]{1,2}/[0-9]{2,4}$' THEN
      v_tgl := to_date(
        lpad(split_part(v_hari, '/', 1), 2, '0') || '-' ||
        lpad(split_part(v_hari, '/', 2), 2, '0') || '-' ||
        CASE
          WHEN length(split_part(v_hari, '/', 3)) = 2
            THEN '20' || split_part(v_hari, '/', 3)
          ELSE split_part(v_hari, '/', 3)
        END,
        'DD-MM-YYYY'
      );
    ELSE
      v_tgl := to_date(replace(replace(v_hari, '.', '-'), '/', '-'), 'DD-MM-YYYY');
    END IF;
  EXCEPTION
    WHEN others THEN
      RETURN NULL;
  END;
  IF v_tgl IS NOT DISTINCT FROM v_wajib THEN
    RETURN 'SBGP0' || v_n;
  END IF;
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_mutasi_cocokkan()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_n integer := 0;
  r record;
  v_rute text;
  v_ada integer;
  v_id bigint;
  v_tgl date;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RETURN 0;
  END IF;
  v_id := public._mutasi_buku_kartu();
  IF v_id IS NULL THEN
    RETURN 0;
  END IF;
  SELECT b.tanggal INTO v_tgl FROM public.setoran_buku b WHERE b.id = v_id;

  FOR r IN
    SELECT m.id, m.berita, m.jumlah, m.status_cocok
    FROM public.mutasi_bank m
    WHERE m.id_setoran_buku = v_id
      AND m.status_cocok <> 'manual'
      AND COALESCE(m.berita, '') !~* '(^|[^[:alnum:]])(db|debet|debit)([^[:alnum:]]|$)'
  LOOP
    v_rute := public.admin_mutasi_rute_dari_berita(r.berita, v_tgl);
    IF v_rute IS NULL THEN
      SELECT COUNT(*)::integer
      INTO v_ada
      FROM public.setoran_pengirim s
      WHERE s.id_setoran_buku = v_id
        AND s.jumlah_transfer = r.jumlah
        AND NOT EXISTS (
          SELECT 1
          FROM public.mutasi_bank x
          WHERE x.id_setoran_buku = v_id
            AND x.id <> r.id
            AND x.rute_pengirim = s.rute_pengirim
            AND x.status_cocok IN ('cocok', 'manual')
        );
      IF v_ada = 1 THEN
        SELECT s.rute_pengirim
        INTO v_rute
        FROM public.setoran_pengirim s
        WHERE s.id_setoran_buku = v_id
          AND s.jumlah_transfer = r.jumlah
          AND NOT EXISTS (
            SELECT 1
            FROM public.mutasi_bank x
            WHERE x.id_setoran_buku = v_id
              AND x.id <> r.id
              AND x.rute_pengirim = s.rute_pengirim
              AND x.status_cocok IN ('cocok', 'manual')
          );
      ELSE
        v_rute := NULL;
      END IF;
    END IF;

    UPDATE public.mutasi_bank
    SET
      rute_pengirim = v_rute,
      status_cocok = CASE WHEN v_rute IS NULL THEN 'tidak_cocok' ELSE 'cocok' END
    WHERE id = r.id
      AND (
        rute_pengirim IS DISTINCT FROM v_rute
        OR status_cocok IS DISTINCT FROM CASE
          WHEN v_rute IS NULL THEN 'tidak_cocok'
          ELSE 'cocok'
        END
      );
    IF FOUND THEN
      v_n := v_n + 1;
    END IF;
  END LOOP;

  RETURN v_n;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_mutasi_unggah(
  p_nama_berkas text,
  p_baris jsonb
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_email text;
  v_n integer := 0;
  r jsonb;
  v_jumlah integer;
  v_berita text;
  v_rek text;
  v_tgl date;
  v_rute text;
  v_id bigint;
  v_tgl_buku date;
  v_tutup boolean;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh unggah mutasi.';
  END IF;
  v_id := public._mutasi_buku_kartu();
  IF v_id IS NULL THEN
    RAISE EXCEPTION 'Tidak ada buku setoran. Mutasi tidak dicatat.';
  END IF;
  SELECT b.tanggal, b.ditutup INTO v_tgl_buku, v_tutup
  FROM public.setoran_buku b
  WHERE b.id = v_id;
  IF v_tutup THEN
    RAISE EXCEPTION 'Buku sudah ditutup. Mutasi tidak diubah.';
  END IF;
  IF p_baris IS NULL OR jsonb_typeof(p_baris) <> 'array' THEN
    RETURN 0;
  END IF;
  IF jsonb_array_length(p_baris) = 0 OR jsonb_array_length(p_baris) > 2000 THEN
    RETURN 0;
  END IF;

  v_email := nullif(btrim(COALESCE(auth.jwt() ->> 'email', '')), '');

  FOR r IN SELECT value FROM jsonb_array_elements(p_baris)
  LOOP
    v_jumlah := GREATEST(COALESCE((r ->> 'jumlah')::integer, 0), 0);
    IF v_jumlah <= 0 THEN
      CONTINUE;
    END IF;
    v_berita := nullif(btrim(COALESCE(r ->> 'berita', '')), '');
    v_rek := nullif(btrim(COALESCE(r ->> 'rekening', '')), '');
    v_tgl := NULL;
    BEGIN
      v_tgl := NULLIF(btrim(COALESCE(r ->> 'tanggal_mutasi', '')), '')::date;
    EXCEPTION
      WHEN others THEN
        v_tgl := NULL;
    END;
    v_rute := upper(nullif(btrim(COALESCE(r ->> 'rute_pengirim', '')), ''));
    IF v_rute IS NOT NULL AND v_rute NOT IN ('SBGP01', 'SBGP02', 'SBGP03', 'SBGP04') THEN
      v_rute := NULL;
    END IF;

    INSERT INTO public.mutasi_bank (
      id_setoran_buku, tanggal, tanggal_mutasi, rekening_alias,
      jumlah, berita, rute_pengirim, status_cocok, nama_berkas, dicatat_oleh
    )
    VALUES (
      v_id, v_tgl_buku, v_tgl, v_rek,
      v_jumlah, v_berita, v_rute,
      CASE WHEN v_rute IS NULL THEN 'tidak_cocok' ELSE 'cocok' END,
      nullif(btrim(COALESCE(p_nama_berkas, '')), ''),
      v_email
    );
    v_n := v_n + 1;
  END LOOP;

  PERFORM public.admin_mutasi_cocokkan();
  RETURN v_n;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_mutasi_lihat()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_id bigint;
  v_baris jsonb;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh masuk web ini.';
  END IF;
  v_id := public._mutasi_buku_kartu();
  IF v_id IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;
  SELECT coalesce(jsonb_agg(q.baris ORDER BY q.jumlah DESC, q.id), '[]'::jsonb)
  INTO v_baris
  FROM (
    SELECT
      m.id,
      m.jumlah,
      jsonb_build_object(
        'id', m.id,
        'tanggal_mutasi', m.tanggal_mutasi,
        'jumlah', m.jumlah,
        'berita', coalesce(m.berita, ''),
        'rekening_alias', coalesce(m.rekening_alias, ''),
        'rute_pengirim', coalesce(m.rute_pengirim, ''),
        'status_cocok', m.status_cocok
      ) AS baris
    FROM public.mutasi_bank m
    WHERE m.id_setoran_buku = v_id
      AND coalesce(m.berita, '') !~* '(^|[^[:alnum:]])(db|debet|debit)([^[:alnum:]]|$)'
  ) q;
  RETURN coalesce(v_baris, '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_mutasi_hapus()
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
SET row_security = off
AS $$
DECLARE
  v_n integer;
  v_id bigint;
  v_tutup boolean;
BEGIN
  IF NOT public.admin_sedang_login() THEN
    RAISE EXCEPTION 'Hanya akun admin yang boleh hapus mutasi.';
  END IF;
  v_id := public._mutasi_buku_kartu();
  IF v_id IS NULL THEN
    RETURN 0;
  END IF;
  SELECT b.ditutup INTO v_tutup FROM public.setoran_buku b WHERE b.id = v_id;
  IF v_tutup THEN
    RAISE EXCEPTION 'Buku sudah ditutup. Mutasi tidak diubah.';
  END IF;
  DELETE FROM public.mutasi_bank WHERE id_setoran_buku = v_id;
  GET DIAGNOSTICS v_n = ROW_COUNT;
  RETURN v_n;
END;
$$;

REVOKE ALL ON FUNCTION public._mutasi_buku_kartu() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public._mutasi_buku_kartu()
  TO postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_mutasi_tanggal_berita_wajib(date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_mutasi_tanggal_berita_wajib(date)
  TO authenticated, postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_mutasi_rute_dari_berita(text, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_mutasi_rute_dari_berita(text, date) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.admin_mutasi_rute_dari_berita(text, date)
  TO postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_mutasi_cocokkan() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_mutasi_cocokkan() FROM authenticated;
GRANT EXECUTE ON FUNCTION public.admin_mutasi_cocokkan()
  TO postgres, service_role;
REVOKE ALL ON FUNCTION public.admin_mutasi_unggah(text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_mutasi_lihat() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_mutasi_hapus() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_mutasi_unggah(text, jsonb)
  TO authenticated, postgres, service_role;
GRANT EXECUTE ON FUNCTION public.admin_mutasi_lihat()
  TO authenticated, postgres, service_role;
GRANT EXECUTE ON FUNCTION public.admin_mutasi_hapus()
  TO authenticated, postgres, service_role;

NOTIFY pgrst, 'reload schema';
