-- Fase 1 kanon: skema baru + tabel inti + helper rumus.
-- SQL Editor sebagai postgres. Boleh diulang (fungsi diganti; tabel tidak di-DROP).
-- TIDAK mengubah public / obos. TIDAK migrasi. TIDAK untuk PostgREST/app.
-- Jangan taruh skema kanon di Extra Schemas API.

CREATE SCHEMA IF NOT EXISTS kanon;

COMMENT ON SCHEMA kanon IS
  'Skema kanonik app baru. Kosong dari app. public = app hidup. obos = app lama.';

REVOKE ALL ON SCHEMA kanon FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA kanon TO postgres, service_role;
GRANT CREATE ON SCHEMA kanon TO postgres;

-- ---------------------------------------------------------------------------
-- Tabel
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS kanon.users (
  email text PRIMARY KEY,
  nama text NOT NULL,
  peran text NOT NULL,
  rute text NOT NULL DEFAULT '',
  is_login boolean NOT NULL DEFAULT false,
  kunci_hp text,
  sesi_login text,
  CONSTRAINT users_email_chk CHECK (btrim(email) <> ''),
  CONSTRAINT users_nama_chk CHECK (btrim(nama) <> ''),
  CONSTRAINT users_peran_chk CHECK (peran IN ('sales', 'gudang', 'admin', 'pengirim'))
);

CREATE UNIQUE INDEX IF NOT EXISTS users_rute_satu_akun_uidx
  ON kanon.users (lower(btrim(rute)))
  WHERE btrim(rute) <> '';

CREATE OR REPLACE FUNCTION kanon.users_rapikan()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.email := lower(btrim(NEW.email));
  NEW.nama := btrim(NEW.nama);
  NEW.peran := lower(btrim(NEW.peran));
  NEW.rute := btrim(COALESCE(NEW.rute, ''));
  NEW.kunci_hp := nullif(btrim(NEW.kunci_hp), '');
  NEW.sesi_login := nullif(btrim(NEW.sesi_login), '');
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS users_rapikan_trg ON kanon.users;
CREATE TRIGGER users_rapikan_trg
  BEFORE INSERT OR UPDATE ON kanon.users
  FOR EACH ROW EXECUTE PROCEDURE kanon.users_rapikan();

CREATE TABLE IF NOT EXISTS kanon.target_sales (
  email text PRIMARY KEY REFERENCES kanon.users (email) ON DELETE CASCADE,
  target_omset integer NOT NULL DEFAULT 0,
  target_persen_laba numeric NOT NULL DEFAULT 0,
  CONSTRAINT target_sales_omset_chk CHECK (target_omset >= 0),
  CONSTRAINT target_sales_persen_chk CHECK (target_persen_laba >= 0)
);

CREATE TABLE IF NOT EXISTS kanon.pelanggan (
  id_pelanggan text PRIMARY KEY,
  nama_pelanggan text NOT NULL,
  rute text,
  visit text,
  urutan integer,
  latitude double precision,
  longitude double precision,
  aktif boolean NOT NULL DEFAULT true,
  CONSTRAINT pelanggan_id_chk CHECK (btrim(id_pelanggan) <> ''),
  CONSTRAINT pelanggan_nama_chk CHECK (btrim(nama_pelanggan) <> '')
);

CREATE INDEX IF NOT EXISTS pelanggan_rute_urutan_idx
  ON kanon.pelanggan (rute, urutan);

CREATE TABLE IF NOT EXISTS kanon.barang (
  id_barang text PRIMARY KEY,
  id_grup text,
  nama_barang text NOT NULL,
  kategori text,
  stok numeric(14, 4) NOT NULL DEFAULT 0,
  harga_beli integer NOT NULL DEFAULT 0,
  harga_jual integer NOT NULL DEFAULT 0,
  min_strat_1 integer NOT NULL DEFAULT 0,
  jual_strat_1 integer NOT NULL DEFAULT 0,
  min_strat_2 integer NOT NULL DEFAULT 0,
  jual_strat_2 integer NOT NULL DEFAULT 0,
  min_strat_3 integer NOT NULL DEFAULT 0,
  jual_strat_3 integer NOT NULL DEFAULT 0,
  min_strat_4 integer NOT NULL DEFAULT 0,
  jual_strat_4 integer NOT NULL DEFAULT 0,
  min_strat_5 integer NOT NULL DEFAULT 0,
  jual_strat_5 integer NOT NULL DEFAULT 0,
  id_supplier_utama integer,
  CONSTRAINT barang_id_chk CHECK (btrim(id_barang) <> ''),
  CONSTRAINT barang_nama_chk CHECK (btrim(nama_barang) <> ''),
  CONSTRAINT barang_stok_chk CHECK (stok >= 0),
  CONSTRAINT barang_harga_chk CHECK (harga_beli >= 0 AND harga_jual >= 0)
);

CREATE INDEX IF NOT EXISTS barang_grup_idx ON kanon.barang (id_grup);

CREATE TABLE IF NOT EXISTS kanon.rute_peta (
  rute_sales text PRIMARY KEY,
  rute_pengirim text NOT NULL,
  CONSTRAINT rute_peta_sales_chk CHECK (btrim(rute_sales) <> ''),
  CONSTRAINT rute_peta_pengirim_chk CHECK (btrim(rute_pengirim) <> '')
);

CREATE INDEX IF NOT EXISTS rute_peta_pengirim_idx
  ON kanon.rute_peta (rute_pengirim);

INSERT INTO kanon.rute_peta (rute_sales, rute_pengirim) VALUES
  ('SBGS01', 'SBGP01'),
  ('SBGS02', 'SBGP01'),
  ('SBGS03', 'SBGP02'),
  ('SBGS04', 'SBGP02'),
  ('SBGS05', 'SBGP03'),
  ('SBGS06', 'SBGP03'),
  ('SBGS07', 'SBGP04'),
  ('SBGS08', 'SBGP04')
ON CONFLICT (rute_sales) DO NOTHING;

CREATE TABLE IF NOT EXISTS kanon.setoran_buku (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  waktu_buka timestamptz NOT NULL DEFAULT clock_timestamp(),
  waktu_tutup timestamptz,
  ditutup boolean NOT NULL DEFAULT false,
  CONSTRAINT setoran_buku_tutup_chk CHECK (
    NOT ditutup OR waktu_tutup IS NOT NULL
  )
);

COMMENT ON COLUMN kanon.setoran_buku.tanggal IS
  'Label Jakarta saat buku dibuka. Bukan identitas nota.';

CREATE UNIQUE INDEX IF NOT EXISTS setoran_buku_terbuka_uidx
  ON kanon.setoran_buku ((ditutup))
  WHERE NOT ditutup;
CREATE INDEX IF NOT EXISTS setoran_buku_tanggal_idx
  ON kanon.setoran_buku (tanggal DESC);

CREATE TABLE IF NOT EXISTS kanon.lokasi_gudang (
  id text PRIMARY KEY,
  nama text NOT NULL,
  latitude double precision,
  longitude double precision,
  CONSTRAINT lokasi_gudang_id_chk CHECK (btrim(id) <> ''),
  CONSTRAINT lokasi_gudang_nama_chk CHECK (btrim(nama) <> '')
);

INSERT INTO kanon.lokasi_gudang (id, nama, latitude, longitude)
VALUES ('utama', 'Gudang Utama', NULL, NULL)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS kanon.absensi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL REFERENCES kanon.users (email),
  peran text NOT NULL,
  rute text,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  id_setoran_buku bigint REFERENCES kanon.setoran_buku (id),
  CONSTRAINT absensi_peran_chk CHECK (peran IN ('gudang', 'pengirim', 'admin')),
  CONSTRAINT absensi_waktu_chk CHECK (
    waktu_keluar IS NULL
    OR (waktu_masuk IS NOT NULL AND waktu_keluar >= waktu_masuk)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS absensi_sesi_terbuka_uidx
  ON kanon.absensi (lower(email))
  WHERE waktu_keluar IS NULL;
CREATE INDEX IF NOT EXISTS absensi_setoran_buku_idx
  ON kanon.absensi (id_setoran_buku);

CREATE TABLE IF NOT EXISTS kanon.transaksi (
  id_transaksi text PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES kanon.pelanggan (id_pelanggan),
  nama_pelanggan text NOT NULL,
  rute text NOT NULL,
  status text NOT NULL DEFAULT 'diproses',
  waktu_order timestamptz NOT NULL DEFAULT timezone('utc', now()),
  waktu_packed timestamptz,
  waktu_actual timestamptz,
  pending boolean NOT NULL DEFAULT false,
  id_setoran_buku bigint REFERENCES kanon.setoran_buku (id),
  CONSTRAINT transaksi_id_chk CHECK (btrim(id_transaksi) <> ''),
  CONSTRAINT transaksi_nama_chk CHECK (btrim(nama_pelanggan) <> ''),
  CONSTRAINT transaksi_rute_chk CHECK (btrim(rute) <> ''),
  CONSTRAINT transaksi_status_chk CHECK (
    status IN ('diproses', 'dikirim', 'terkirim', 'batal')
  ),
  CONSTRAINT transaksi_pending_chk CHECK (
    NOT pending
    OR (status = 'dikirim' AND waktu_actual IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS transaksi_rute_order_idx
  ON kanon.transaksi (rute, waktu_order DESC);
CREATE INDEX IF NOT EXISTS transaksi_pelanggan_idx
  ON kanon.transaksi (id_pelanggan);
CREATE INDEX IF NOT EXISTS transaksi_setoran_buku_idx
  ON kanon.transaksi (id_setoran_buku);

CREATE TABLE IF NOT EXISTS kanon.transaksi_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_transaksi text NOT NULL REFERENCES kanon.transaksi (id_transaksi) ON DELETE CASCADE,
  id_barang text NOT NULL REFERENCES kanon.barang (id_barang),
  id_grup text,
  nama_barang text NOT NULL,
  harga_beli integer NOT NULL,
  harga_jual integer NOT NULL,
  qty_order integer NOT NULL,
  qty_packed integer,
  qty_actual integer,
  subtotal_beli_order integer GENERATED ALWAYS AS (qty_order * harga_beli) STORED,
  subtotal_beli_packed integer GENERATED ALWAYS AS (qty_packed * harga_beli) STORED,
  subtotal_beli_actual integer GENERATED ALWAYS AS (qty_actual * harga_beli) STORED,
  min_strat_1 integer NOT NULL DEFAULT 0,
  jual_strat_1 integer NOT NULL DEFAULT 0,
  min_strat_2 integer NOT NULL DEFAULT 0,
  jual_strat_2 integer NOT NULL DEFAULT 0,
  min_strat_3 integer NOT NULL DEFAULT 0,
  jual_strat_3 integer NOT NULL DEFAULT 0,
  min_strat_4 integer NOT NULL DEFAULT 0,
  jual_strat_4 integer NOT NULL DEFAULT 0,
  min_strat_5 integer NOT NULL DEFAULT 0,
  jual_strat_5 integer NOT NULL DEFAULT 0,
  CONSTRAINT transaksi_items_nama_chk CHECK (btrim(nama_barang) <> ''),
  CONSTRAINT transaksi_items_harga_chk CHECK (harga_beli >= 0 AND harga_jual >= 0),
  CONSTRAINT transaksi_items_order_chk CHECK (qty_order >= 0),
  CONSTRAINT transaksi_items_packed_chk CHECK (qty_packed IS NULL OR qty_packed >= 0),
  CONSTRAINT transaksi_items_actual_chk CHECK (qty_actual IS NULL OR qty_actual >= 0),
  CONSTRAINT transaksi_items_sku UNIQUE (id_transaksi, id_barang)
);

CREATE INDEX IF NOT EXISTS transaksi_items_transaksi_idx
  ON kanon.transaksi_items (id_transaksi);

CREATE TABLE IF NOT EXISTS kanon.setoran_buku_pending_foto (
  id_setoran_buku bigint NOT NULL
    REFERENCES kanon.setoran_buku (id) ON DELETE CASCADE,
  id_transaksi text NOT NULL,
  PRIMARY KEY (id_setoran_buku, id_transaksi)
);

CREATE INDEX IF NOT EXISTS setoran_buku_pending_foto_nota_idx
  ON kanon.setoran_buku_pending_foto (id_transaksi);

CREATE TABLE IF NOT EXISTS kanon.stok_opname (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES kanon.setoran_buku (id),
  tanggal date NOT NULL,
  id_barang text NOT NULL REFERENCES kanon.barang (id_barang),
  nama_barang text NOT NULL,
  stok_awal numeric(14, 4) NOT NULL DEFAULT 0,
  qty_masuk numeric(14, 4) NOT NULL DEFAULT 0,
  qty_packed numeric(14, 4) NOT NULL DEFAULT 0,
  qty_batal numeric(14, 4) NOT NULL DEFAULT 0,
  qty_retur numeric(14, 4) NOT NULL DEFAULT 0,
  stok_hitung numeric(14, 4) GENERATED ALWAYS AS (
    stok_awal + qty_masuk - qty_packed + qty_batal + qty_retur
  ) STORED,
  stok_fisik numeric(14, 4),
  selisih numeric(14, 4) GENERATED ALWAYS AS (
    stok_fisik - (stok_awal + qty_masuk - qty_packed + qty_batal + qty_retur)
  ) STORED,
  dicek_stok_oleh text,
  putusan text,
  nilai_putusan integer,
  harga_beli_putusan integer,
  qty_selisih_putusan numeric(14, 4),
  kasbon_email text,
  kasbon_nama text,
  waktu_putusan timestamptz,
  CONSTRAINT stok_opname_nama_chk CHECK (btrim(nama_barang) <> ''),
  CONSTRAINT stok_opname_angka_chk CHECK (
    stok_awal >= 0
    AND qty_masuk >= 0
    AND qty_packed >= 0
    AND qty_batal >= 0
    AND qty_retur >= 0
    AND qty_batal <= qty_packed
    AND (stok_fisik IS NULL OR stok_fisik >= 0)
  ),
  CONSTRAINT stok_opname_putusan_chk CHECK (
    putusan IS NULL
    OR (
      putusan IN ('kasbon', 'beban', 'margin_plus')
      AND nilai_putusan IS NOT NULL
      AND nilai_putusan >= 0
      AND harga_beli_putusan IS NOT NULL
      AND harga_beli_putusan >= 0
      AND (
        putusan <> 'kasbon'
        OR (
          kasbon_email IS NOT NULL
          AND btrim(kasbon_email) <> ''
          AND kasbon_nama IS NOT NULL
          AND btrim(kasbon_nama) <> ''
        )
      )
    )
  ),
  CONSTRAINT stok_opname_sku_buku UNIQUE (id_setoran_buku, id_barang)
);

CREATE TABLE IF NOT EXISTS kanon.kasbon (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL REFERENCES kanon.users (email),
  nama text NOT NULL,
  nilai integer NOT NULL,
  id_setoran_buku bigint NOT NULL REFERENCES kanon.setoran_buku (id),
  id_barang text NOT NULL,
  waktu timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT kasbon_nilai_chk CHECK (nilai > 0),
  CONSTRAINT kasbon_nama_chk CHECK (btrim(nama) <> '')
);

CREATE TABLE IF NOT EXISTS kanon.kunjungan_sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES kanon.pelanggan (id_pelanggan),
  rute text NOT NULL,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  jarak double precision NOT NULL DEFAULT 0,
  CONSTRAINT kunjungan_sales_rute_chk CHECK (btrim(rute) <> ''),
  CONSTRAINT kunjungan_sales_jarak_chk CHECK (jarak >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS kunjungan_sales_toko_hari_uidx
  ON kanon.kunjungan_sales (id_pelanggan, tanggal);

CREATE TABLE IF NOT EXISTS kanon.kunjungan_pengirim (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES kanon.pelanggan (id_pelanggan),
  rute_pengirim text NOT NULL,
  rute_sales text NOT NULL,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  jarak double precision NOT NULL DEFAULT 0,
  CONSTRAINT kunjungan_pengirim_rute_chk CHECK (
    btrim(rute_pengirim) <> '' AND btrim(rute_sales) <> ''
  ),
  CONSTRAINT kunjungan_pengirim_jarak_chk CHECK (jarak >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS kunjungan_pengirim_toko_hari_uidx
  ON kanon.kunjungan_pengirim (rute_pengirim, id_pelanggan, tanggal);

CREATE TABLE IF NOT EXISTS kanon.retur_toko (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES kanon.setoran_buku (id),
  tanggal date NOT NULL,
  rute_pengirim text NOT NULL,
  id_pelanggan text NOT NULL,
  kode_barang text NOT NULL,
  nama_barang text NOT NULL DEFAULT '',
  qty integer NOT NULL,
  harga_jual integer NOT NULL DEFAULT 0,
  waktu_catat timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT retur_toko_qty_chk CHECK (qty > 0),
  CONSTRAINT retur_toko_harga_chk CHECK (harga_jual >= 0),
  CONSTRAINT retur_toko_rute_chk CHECK (btrim(rute_pengirim) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS retur_toko_buku_uidx
  ON kanon.retur_toko (id_setoran_buku, rute_pengirim, id_pelanggan, kode_barang);

CREATE TABLE IF NOT EXISTS kanon.supplier (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  CONSTRAINT supplier_nama_chk CHECK (btrim(nama) <> ''),
  CONSTRAINT supplier_nama_uk UNIQUE (nama)
);

CREATE TABLE IF NOT EXISTS kanon.supplier_harga (
  id_supplier integer NOT NULL REFERENCES kanon.supplier (id),
  id_barang text NOT NULL REFERENCES kanon.barang (id_barang),
  harga_beli integer NOT NULL DEFAULT 0,
  PRIMARY KEY (id_supplier, id_barang),
  CONSTRAINT supplier_harga_beli_chk CHECK (harga_beli >= 0)
);

CREATE TABLE IF NOT EXISTS kanon.barang_masuk (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  id_supplier integer NOT NULL REFERENCES kanon.supplier (id),
  id_barang text NOT NULL REFERENCES kanon.barang (id_barang),
  qty numeric(14, 4) NOT NULL DEFAULT 0,
  nilai integer NOT NULL DEFAULT 0,
  id_setoran_buku bigint REFERENCES kanon.setoran_buku (id),
  CONSTRAINT barang_masuk_qty_chk CHECK (qty > 0),
  CONSTRAINT barang_masuk_nilai_chk CHECK (nilai >= 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS barang_masuk_buku_uidx
  ON kanon.barang_masuk (id_setoran_buku, id_supplier, id_barang)
  WHERE id_setoran_buku IS NOT NULL;

CREATE TABLE IF NOT EXISTS kanon.ongkir (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  id_supplier integer NOT NULL REFERENCES kanon.supplier (id),
  jumlah integer NOT NULL DEFAULT 0,
  id_setoran_buku bigint REFERENCES kanon.setoran_buku (id),
  CONSTRAINT ongkir_jumlah_chk CHECK (jumlah >= 0)
);

CREATE TABLE IF NOT EXISTS kanon.setoran_pengirim (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rute_pengirim text NOT NULL,
  id_setoran_buku bigint NOT NULL REFERENCES kanon.setoran_buku (id),
  jumlah_transfer integer NOT NULL DEFAULT 0,
  jumlah_tunai integer NOT NULL DEFAULT 0,
  jumlah_bop integer NOT NULL DEFAULT 0,
  kasbon_supir integer NOT NULL DEFAULT 0,
  kasbon_kenek integer NOT NULL DEFAULT 0,
  waktu_setor timestamptz NOT NULL DEFAULT clock_timestamp(),
  dicatat_oleh text NOT NULL DEFAULT '',
  dicatat_rute text NOT NULL DEFAULT '',
  CONSTRAINT setoran_pengirim_rute_chk CHECK (btrim(rute_pengirim) <> ''),
  CONSTRAINT setoran_pengirim_uang_chk CHECK (
    jumlah_transfer >= 0
    AND jumlah_tunai >= 0
    AND jumlah_bop >= 0
    AND jumlah_bop <= 170000
    AND kasbon_supir >= 0
    AND kasbon_kenek >= 0
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS setoran_pengirim_rute_buku_uidx
  ON kanon.setoran_pengirim (rute_pengirim, id_setoran_buku);

CREATE TABLE IF NOT EXISTS kanon.setoran_kartu_simpan (
  id_setoran_buku bigint PRIMARY KEY REFERENCES kanon.setoran_buku (id),
  isi jsonb NOT NULL,
  waktu_simpan timestamptz NOT NULL DEFAULT clock_timestamp(),
  dicatat_oleh text
);

CREATE TABLE IF NOT EXISTS kanon.mutasi_bank (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES kanon.setoran_buku (id),
  tanggal date NOT NULL,
  tanggal_mutasi date,
  rekening_alias text,
  jumlah integer NOT NULL DEFAULT 0,
  berita text,
  rute_pengirim text,
  status_cocok text NOT NULL DEFAULT 'tidak_cocok',
  nama_berkas text,
  dicatat_oleh text,
  waktu_unggah timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT mutasi_bank_status_chk
    CHECK (status_cocok IN ('cocok', 'manual', 'tidak_cocok')),
  CONSTRAINT mutasi_bank_jumlah_chk CHECK (jumlah >= 0)
);

CREATE INDEX IF NOT EXISTS mutasi_bank_buku_idx
  ON kanon.mutasi_bank (id_setoran_buku);

-- Tabel hanya postgres/service_role. App tidak baca kanon.
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users', 'target_sales', 'pelanggan', 'barang', 'rute_peta', 'setoran_buku',
    'lokasi_gudang', 'absensi', 'transaksi', 'transaksi_items',
    'setoran_buku_pending_foto', 'stok_opname', 'kasbon', 'kunjungan_sales',
    'kunjungan_pengirim', 'retur_toko', 'supplier', 'supplier_harga',
    'barang_masuk', 'ongkir', 'setoran_pengirim', 'setoran_kartu_simpan',
    'mutasi_bank'
  ]
  LOOP
    EXECUTE format('REVOKE ALL ON TABLE kanon.%I FROM PUBLIC, anon, authenticated', t);
    EXECUTE format(
      'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE kanon.%I TO postgres, service_role',
      t
    );
    EXECUTE format('ALTER TABLE kanon.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE kanon.%I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format('DROP POLICY IF EXISTS kanon_postgres ON kanon.%I', t);
    EXECUTE format(
      'CREATE POLICY kanon_postgres ON kanon.%I TO postgres, service_role USING (true) WITH CHECK (true)',
      t
    );
  END LOOP;
END;
$$;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA kanon TO postgres, service_role;

-- ---------------------------------------------------------------------------
-- Helper rumus (satu sumber; kartu nanti hanya memanggil ini)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION kanon.hari_jakarta(p timestamptz)
RETURNS date
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT (p AT TIME ZONE 'Asia/Jakarta')::date;
$$;

CREATE OR REPLACE FUNCTION kanon.grup_rute(p_rute text)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT regexp_replace(upper(btrim(COALESCE(p_rute, ''))), '[DH]$', '');
$$;

CREATE OR REPLACE FUNCTION kanon.harga_jual_strata(
  p_dasar integer,
  p_qty integer,
  p_min1 integer,
  p_jual1 integer,
  p_min2 integer,
  p_jual2 integer,
  p_min3 integer,
  p_jual3 integer,
  p_min4 integer,
  p_jual4 integer,
  p_min5 integer,
  p_jual5 integer
)
RETURNS integer
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT COALESCE(
    (
      SELECT s.jual
      FROM (
        VALUES
          (p_min5, p_jual5),
          (p_min4, p_jual4),
          (p_min3, p_jual3),
          (p_min2, p_jual2),
          (p_min1, p_jual1)
      ) AS s(min, jual)
      WHERE COALESCE(p_qty, 0) >= s.min
        AND s.min > 0
        AND s.jual > 0
      ORDER BY s.min DESC
      LIMIT 1
    ),
    GREATEST(COALESCE(p_dasar, 0), 0)
  );
$$;

-- Nota batal = packed penuh. Terkirim = sisa tebus (packed − actual). Selain itu 0.
CREATE OR REPLACE FUNCTION kanon.omset_batal(
  p_status text,
  p_packed numeric,
  p_actual numeric
)
RETURNS bigint
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_status = 'batal' THEN round(coalesce(p_packed, 0))::bigint
    WHEN p_status = 'terkirim' THEN
      greatest(round(coalesce(p_packed, 0) - coalesce(p_actual, 0)), 0)::bigint
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION kanon.qty_batal(
  p_status text,
  p_packed numeric,
  p_actual numeric
)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_status = 'batal' THEN coalesce(p_packed, 0)
    WHEN p_status = 'terkirim' THEN
      greatest(coalesce(p_packed, 0) - coalesce(p_actual, 0), 0)
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION kanon.omset_pending(
  p_pending boolean,
  p_packed numeric
)
RETURNS bigint
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN coalesce(p_pending, false) THEN round(coalesce(p_packed, 0))::bigint
    ELSE 0
  END;
$$;

CREATE OR REPLACE FUNCTION kanon.omset_actual(
  p_status text,
  p_actual numeric
)
RETURNS bigint
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE
    WHEN p_status = 'batal' THEN 0
    ELSE round(coalesce(p_actual, 0))::bigint
  END;
$$;

-- Admin kartu: cap buku ini, atau (buku hidup) packed belum ber-id.
-- Tidak menarik terkirim buku lain hanya karena actual hari ini.
CREATE OR REPLACE FUNCTION kanon.nota_ikut_admin(
  p_id_buku bigint,
  p_tgl date,
  p_tutup boolean,
  p_id_setoran_buku bigint,
  p_status text,
  p_waktu_actual timestamptz
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    p_id_buku IS NOT NULL
    AND (
      p_id_setoran_buku = p_id_buku
      OR (
        p_id_setoran_buku IS NULL
        AND NOT coalesce(p_tutup, false)
        AND (
          p_status = 'dikirim'
          OR (
            p_status IN ('terkirim', 'batal')
            AND p_waktu_actual IS NOT NULL
            AND kanon.hari_jakarta(p_waktu_actual) = p_tgl
          )
        )
      )
    );
$$;

-- Gudang packing: cap buku, atau order hari itu belum tercap (buku hidup / belum ada buku).
CREATE OR REPLACE FUNCTION kanon.nota_ikut_gudang(
  p_id_buku bigint,
  p_tgl date,
  p_hidup boolean,
  p_id_setoran_buku bigint,
  p_waktu_order timestamptz
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    p_tgl IS NOT NULL
    AND p_waktu_order IS NOT NULL
    AND (
      (p_id_buku IS NOT NULL AND p_id_setoran_buku = p_id_buku)
      OR (
        kanon.hari_jakarta(p_waktu_order) = p_tgl
        AND p_id_setoran_buku IS NULL
        AND (p_id_buku IS NULL OR coalesce(p_hidup, false))
      )
    );
$$;

CREATE OR REPLACE FUNCTION kanon.nota_ikut_pengirim(
  p_id_buku bigint,
  p_tgl date,
  p_hidup boolean,
  p_id_setoran_buku bigint,
  p_status text,
  p_waktu_order timestamptz,
  p_waktu_actual timestamptz,
  p_tanggal_lihat date
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT
    (
      p_id_buku IS NOT NULL
      AND p_id_setoran_buku = p_id_buku
    )
    OR (
      p_tgl IS NOT NULL
      AND p_waktu_order IS NOT NULL
      AND kanon.hari_jakarta(p_waktu_order) = p_tgl
      AND p_id_setoran_buku IS NULL
      AND p_status = 'dikirim'
      AND (p_id_buku IS NULL OR coalesce(p_hidup, false))
    )
    OR (
      p_id_buku IS NULL
      AND p_id_setoran_buku IS NULL
      AND p_status IN ('terkirim', 'batal')
      AND p_waktu_actual IS NOT NULL
      AND p_tanggal_lihat IS NOT NULL
      AND kanon.hari_jakarta(p_waktu_actual) = p_tanggal_lihat
    );
$$;

-- Halaman pending: flag nota, atau foto di buku tutup.
CREATE OR REPLACE FUNCTION kanon.pending_halaman(
  p_pending boolean
)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT coalesce(p_pending, false);
$$;

CREATE OR REPLACE VIEW kanon.v_transaksi_item AS
SELECT
  z.*,
  z.qty_order * z.harga_jual_order AS subtotal_jual_order,
  CASE
    WHEN z.qty_packed IS NULL THEN NULL
    ELSE z.qty_packed * z.harga_jual_packed
  END AS subtotal_jual_packed,
  CASE
    WHEN z.qty_actual IS NULL THEN NULL
    ELSE z.qty_actual * z.harga_jual_actual
  END AS subtotal_jual_actual
FROM (
  SELECT
    i.id,
    i.id_transaksi,
    i.id_barang,
    i.id_grup,
    i.nama_barang,
    i.harga_beli,
    i.harga_jual,
    i.qty_order,
    i.qty_packed,
    i.qty_actual,
    i.subtotal_beli_order,
    i.subtotal_beli_packed,
    i.subtotal_beli_actual,
    i.min_strat_1,
    i.jual_strat_1,
    i.min_strat_2,
    i.jual_strat_2,
    i.min_strat_3,
    i.jual_strat_3,
    i.min_strat_4,
    i.jual_strat_4,
    i.min_strat_5,
    i.jual_strat_5,
    kanon.harga_jual_strata(
      COALESCE(i.harga_jual, 0),
      COALESCE(SUM(i.qty_order) OVER w, 0)::integer,
      i.min_strat_1, i.jual_strat_1,
      i.min_strat_2, i.jual_strat_2,
      i.min_strat_3, i.jual_strat_3,
      i.min_strat_4, i.jual_strat_4,
      i.min_strat_5, i.jual_strat_5
    ) AS harga_jual_order,
    CASE WHEN i.qty_packed IS NULL THEN NULL ELSE kanon.harga_jual_strata(
      COALESCE(i.harga_jual, 0),
      COALESCE(SUM(COALESCE(i.qty_packed, 0)) OVER w, 0)::integer,
      i.min_strat_1, i.jual_strat_1,
      i.min_strat_2, i.jual_strat_2,
      i.min_strat_3, i.jual_strat_3,
      i.min_strat_4, i.jual_strat_4,
      i.min_strat_5, i.jual_strat_5
    ) END AS harga_jual_packed,
    CASE WHEN i.qty_actual IS NULL THEN NULL ELSE kanon.harga_jual_strata(
      COALESCE(i.harga_jual, 0),
      COALESCE(SUM(COALESCE(i.qty_actual, 0)) OVER w, 0)::integer,
      i.min_strat_1, i.jual_strat_1,
      i.min_strat_2, i.jual_strat_2,
      i.min_strat_3, i.jual_strat_3,
      i.min_strat_4, i.jual_strat_4,
      i.min_strat_5, i.jual_strat_5
    ) END AS harga_jual_actual
  FROM kanon.transaksi_items i
  WINDOW w AS (
    PARTITION BY i.id_transaksi,
      COALESCE(NULLIF(btrim(i.id_grup), ''), i.id_barang)
  )
) z;

GRANT SELECT ON kanon.v_transaksi_item TO postgres, service_role;
REVOKE ALL ON kanon.v_transaksi_item FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE VIEW kanon.v_omset_nota AS
SELECT
  t.id_transaksi,
  t.id_pelanggan,
  t.nama_pelanggan,
  t.rute,
  t.status,
  t.pending,
  t.waktu_order,
  t.waktu_packed,
  t.waktu_actual,
  t.id_setoran_buku,
  coalesce(sum(i.subtotal_jual_order), 0)::bigint AS jual_order,
  coalesce(sum(i.subtotal_jual_packed), 0)::bigint AS jual_packed,
  coalesce(sum(i.subtotal_jual_actual), 0)::bigint AS jual_actual,
  kanon.omset_batal(
    t.status,
    coalesce(sum(i.subtotal_jual_packed), 0),
    coalesce(sum(i.subtotal_jual_actual), 0)
  ) AS jual_batal,
  kanon.omset_pending(
    t.pending,
    coalesce(sum(i.subtotal_jual_packed), 0)
  ) AS jual_pending,
  kanon.omset_actual(
    t.status,
    coalesce(sum(i.subtotal_jual_actual), 0)
  ) AS jual_actual_kartu
FROM kanon.transaksi t
LEFT JOIN kanon.v_transaksi_item i ON i.id_transaksi = t.id_transaksi
GROUP BY
  t.id_transaksi, t.id_pelanggan, t.nama_pelanggan, t.rute,
  t.status, t.pending, t.waktu_order, t.waktu_packed, t.waktu_actual,
  t.id_setoran_buku;

GRANT SELECT ON kanon.v_omset_nota TO postgres, service_role;
REVOKE ALL ON kanon.v_omset_nota FROM PUBLIC, anon, authenticated;

DO $$
DECLARE
  f record;
BEGIN
  FOR f IN
    SELECT p.proname, pg_get_function_identity_arguments(p.oid) AS args
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'kanon'
  LOOP
    EXECUTE format(
      'REVOKE ALL ON FUNCTION kanon.%I(%s) FROM PUBLIC, anon, authenticated',
      f.proname, f.args
    );
    EXECUTE format(
      'GRANT EXECUTE ON FUNCTION kanon.%I(%s) TO postgres, service_role',
      f.proname, f.args
    );
  END LOOP;
END;
$$;
