-- Skema obos baru: drop bekas (kanon + obos lama), tabel inti, seed konfigurasi.
-- SQL Editor sebagai postgres. public tidak diubah. Tidak migrasi. Tidak untuk API.
-- Jangan taruh obos di Extra Schemas API.
-- Ulangi = DROP CASCADE: semua isi obos hilang.

DROP SCHEMA IF EXISTS kanon CASCADE;
DROP SCHEMA IF EXISTS obos CASCADE;

CREATE SCHEMA obos;
COMMENT ON SCHEMA obos IS
  'Skema kanonik app baru. Kosong dari histori. public = app hidup.';

REVOKE ALL ON SCHEMA obos FROM PUBLIC, anon, authenticated;
GRANT USAGE ON SCHEMA obos TO postgres, service_role;
GRANT CREATE ON SCHEMA obos TO postgres;

-- 1. Tanpa FK ke tabel obos lain
CREATE TABLE obos.users (
  email text PRIMARY KEY,
  nama text NOT NULL,
  peran text NOT NULL,
  rute text NOT NULL DEFAULT '',
  is_login boolean NOT NULL DEFAULT false,
  kunci_hp text,
  sesi_login text,
  CONSTRAINT users_email_chk CHECK (btrim(email) <> ''),
  CONSTRAINT users_nama_chk CHECK (btrim(nama) <> ''),
  CONSTRAINT users_peran_chk CHECK (peran IN ('sales', 'gudang', 'admin', 'pengirim'))
);

CREATE UNIQUE INDEX users_rute_satu_akun_uidx
  ON obos.users (lower(btrim(rute)))
  WHERE btrim(rute) <> '';

CREATE OR REPLACE FUNCTION obos.users_rapikan()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.email := lower(btrim(NEW.email));
  NEW.nama := btrim(NEW.nama);
  NEW.peran := lower(btrim(NEW.peran));
  NEW.rute := btrim(COALESCE(NEW.rute, ''));
  NEW.kunci_hp := nullif(btrim(NEW.kunci_hp), '');
  NEW.sesi_login := nullif(btrim(NEW.sesi_login), '');
  RETURN NEW;
END;
$$;

CREATE TRIGGER users_rapikan_trg
  BEFORE INSERT OR UPDATE ON obos.users
  FOR EACH ROW EXECUTE PROCEDURE obos.users_rapikan();

CREATE TABLE obos.lokasi_gudang (
  id text PRIMARY KEY,
  nama text NOT NULL,
  latitude double precision,
  longitude double precision,
  CONSTRAINT lokasi_gudang_id_chk CHECK (btrim(id) <> ''),
  CONSTRAINT lokasi_gudang_nama_chk CHECK (btrim(nama) <> '')
);

INSERT INTO obos.lokasi_gudang (id, nama, latitude, longitude)
VALUES ('utama', 'Gudang Utama', NULL, NULL);

CREATE TABLE obos.rute_peta (
  rute_sales text PRIMARY KEY,
  rute_pengirim text NOT NULL,
  CONSTRAINT rute_peta_sales_chk CHECK (btrim(rute_sales) <> ''),
  CONSTRAINT rute_peta_pengirim_chk CHECK (btrim(rute_pengirim) <> '')
);

CREATE INDEX rute_peta_pengirim_idx ON obos.rute_peta (rute_pengirim);

INSERT INTO obos.rute_peta (rute_sales, rute_pengirim) VALUES
  ('SBGS01', 'SBGP01'),
  ('SBGS02', 'SBGP01'),
  ('SBGS03', 'SBGP02'),
  ('SBGS04', 'SBGP02'),
  ('SBGS05', 'SBGP03'),
  ('SBGS06', 'SBGP03'),
  ('SBGS07', 'SBGP04'),
  ('SBGS08', 'SBGP04');

CREATE TABLE obos.supplier (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama text NOT NULL,
  aktif boolean NOT NULL DEFAULT true,
  CONSTRAINT supplier_nama_chk CHECK (btrim(nama) <> ''),
  CONSTRAINT supplier_nama_uk UNIQUE (nama)
);

-- 2. Master
CREATE TABLE obos.target_sales (
  email text PRIMARY KEY REFERENCES obos.users (email) ON DELETE CASCADE,
  target_omset integer NOT NULL DEFAULT 0,
  target_persen_laba numeric NOT NULL DEFAULT 0,
  CONSTRAINT target_sales_omset_chk CHECK (target_omset >= 0),
  CONSTRAINT target_sales_persen_chk CHECK (target_persen_laba >= 0)
);

CREATE TABLE obos.pelanggan (
  id_pelanggan text PRIMARY KEY,
  nama_pelanggan text NOT NULL,
  rute text,
  visit text,
  urutan integer,
  latitude double precision,
  longitude double precision,
  aktif boolean NOT NULL DEFAULT true,
  CONSTRAINT pelanggan_id_chk CHECK (btrim(id_pelanggan) <> ''),
  CONSTRAINT pelanggan_nama_chk CHECK (btrim(nama_pelanggan) <> '')
);

CREATE INDEX pelanggan_rute_urutan_idx ON obos.pelanggan (rute, urutan);

CREATE TABLE obos.barang (
  id_barang text PRIMARY KEY,
  id_grup text,
  nama_barang text NOT NULL,
  kategori text,
  stok numeric(14, 4) NOT NULL DEFAULT 0,
  harga_beli integer NOT NULL DEFAULT 0,
  harga_jual integer NOT NULL DEFAULT 0,
  min_strat_1 integer NOT NULL DEFAULT 0,
  jual_strat_1 integer NOT NULL DEFAULT 0,
  min_strat_2 integer NOT NULL DEFAULT 0,
  jual_strat_2 integer NOT NULL DEFAULT 0,
  min_strat_3 integer NOT NULL DEFAULT 0,
  jual_strat_3 integer NOT NULL DEFAULT 0,
  min_strat_4 integer NOT NULL DEFAULT 0,
  jual_strat_4 integer NOT NULL DEFAULT 0,
  min_strat_5 integer NOT NULL DEFAULT 0,
  jual_strat_5 integer NOT NULL DEFAULT 0,
  id_supplier_utama integer REFERENCES obos.supplier (id),
  aktif boolean NOT NULL DEFAULT true,
  CONSTRAINT barang_id_chk CHECK (btrim(id_barang) <> ''),
  CONSTRAINT barang_nama_chk CHECK (btrim(nama_barang) <> ''),
  CONSTRAINT barang_stok_chk CHECK (stok >= 0),
  CONSTRAINT barang_harga_chk CHECK (harga_beli >= 0 AND harga_jual >= 0)
);

CREATE INDEX barang_grup_idx ON obos.barang (id_grup);

COMMENT ON COLUMN obos.barang.aktif IS
  'false = disembunyikan dari katalog lapangan dan opname gudang. Tidak dihapus (FK nota).';

CREATE TABLE obos.supplier_harga (
  id_supplier integer NOT NULL REFERENCES obos.supplier (id),
  id_barang text NOT NULL REFERENCES obos.barang (id_barang),
  harga_beli integer NOT NULL DEFAULT 0,
  PRIMARY KEY (id_supplier, id_barang),
  CONSTRAINT supplier_harga_beli_chk CHECK (harga_beli >= 0)
);

-- 3. Buku lalu yang memakai id_setoran_buku
CREATE TABLE obos.setoran_buku (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  waktu_buka timestamptz NOT NULL DEFAULT clock_timestamp(),
  waktu_tutup timestamptz,
  ditutup boolean NOT NULL DEFAULT false,
  CONSTRAINT setoran_buku_tutup_chk CHECK (
    NOT ditutup OR waktu_tutup IS NOT NULL
  )
);

COMMENT ON COLUMN obos.setoran_buku.tanggal IS
  'Label Jakarta saat buku dibuka. Bukan identitas nota.';

CREATE UNIQUE INDEX setoran_buku_terbuka_uidx
  ON obos.setoran_buku ((ditutup))
  WHERE NOT ditutup;
CREATE INDEX setoran_buku_tanggal_idx ON obos.setoran_buku (tanggal DESC);

CREATE TABLE obos.absensi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL REFERENCES obos.users (email),
  peran text NOT NULL,
  rute text,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  id_setoran_buku bigint REFERENCES obos.setoran_buku (id),
  CONSTRAINT absensi_peran_chk CHECK (peran IN ('gudang', 'pengirim', 'admin')),
  CONSTRAINT absensi_waktu_chk CHECK (
    waktu_keluar IS NULL
    OR (waktu_masuk IS NOT NULL AND waktu_keluar >= waktu_masuk)
  )
);

CREATE UNIQUE INDEX absensi_sesi_terbuka_uidx
  ON obos.absensi (lower(email))
  WHERE waktu_keluar IS NULL;
CREATE INDEX absensi_setoran_buku_idx ON obos.absensi (id_setoran_buku);

CREATE TABLE obos.transaksi (
  id_transaksi text PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES obos.pelanggan (id_pelanggan),
  nama_pelanggan text NOT NULL,
  rute text NOT NULL,
  status text NOT NULL DEFAULT 'diproses',
  waktu_order timestamptz NOT NULL DEFAULT timezone('utc', now()),
  waktu_packed timestamptz,
  waktu_actual timestamptz,
  pending boolean NOT NULL DEFAULT false,
  id_setoran_buku bigint REFERENCES obos.setoran_buku (id),
  CONSTRAINT transaksi_id_chk CHECK (btrim(id_transaksi) <> ''),
  CONSTRAINT transaksi_nama_chk CHECK (btrim(nama_pelanggan) <> ''),
  CONSTRAINT transaksi_rute_chk CHECK (btrim(rute) <> ''),
  CONSTRAINT transaksi_status_chk CHECK (
    status IN ('diproses', 'dikirim', 'terkirim', 'batal')
  ),
  CONSTRAINT transaksi_pending_chk CHECK (
    NOT pending
    OR (status = 'dikirim' AND waktu_actual IS NULL)
  )
);

CREATE INDEX transaksi_rute_order_idx ON obos.transaksi (rute, waktu_order DESC);
CREATE INDEX transaksi_pelanggan_idx ON obos.transaksi (id_pelanggan);
CREATE INDEX transaksi_setoran_buku_idx ON obos.transaksi (id_setoran_buku);

CREATE TABLE obos.transaksi_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_transaksi text NOT NULL REFERENCES obos.transaksi (id_transaksi) ON DELETE CASCADE,
  id_barang text NOT NULL REFERENCES obos.barang (id_barang),
  id_grup text,
  nama_barang text NOT NULL,
  harga_beli integer NOT NULL,
  harga_jual integer NOT NULL,
  qty_order integer NOT NULL,
  qty_packed integer,
  qty_actual integer,
  subtotal_beli_order integer GENERATED ALWAYS AS (qty_order * harga_beli) STORED,
  subtotal_beli_packed integer GENERATED ALWAYS AS (qty_packed * harga_beli) STORED,
  subtotal_beli_actual integer GENERATED ALWAYS AS (qty_actual * harga_beli) STORED,
  min_strat_1 integer NOT NULL DEFAULT 0,
  jual_strat_1 integer NOT NULL DEFAULT 0,
  min_strat_2 integer NOT NULL DEFAULT 0,
  jual_strat_2 integer NOT NULL DEFAULT 0,
  min_strat_3 integer NOT NULL DEFAULT 0,
  jual_strat_3 integer NOT NULL DEFAULT 0,
  min_strat_4 integer NOT NULL DEFAULT 0,
  jual_strat_4 integer NOT NULL DEFAULT 0,
  min_strat_5 integer NOT NULL DEFAULT 0,
  jual_strat_5 integer NOT NULL DEFAULT 0,
  CONSTRAINT transaksi_items_nama_chk CHECK (btrim(nama_barang) <> ''),
  CONSTRAINT transaksi_items_harga_chk CHECK (harga_beli >= 0 AND harga_jual >= 0),
  CONSTRAINT transaksi_items_order_chk CHECK (qty_order >= 0),
  CONSTRAINT transaksi_items_packed_chk CHECK (qty_packed IS NULL OR qty_packed >= 0),
  CONSTRAINT transaksi_items_actual_chk CHECK (qty_actual IS NULL OR qty_actual >= 0),
  CONSTRAINT transaksi_items_sku UNIQUE (id_transaksi, id_barang)
);

CREATE INDEX transaksi_items_transaksi_idx ON obos.transaksi_items (id_transaksi);

CREATE TABLE obos.setoran_buku_pending_foto (
  id_setoran_buku bigint NOT NULL
    REFERENCES obos.setoran_buku (id) ON DELETE CASCADE,
  id_transaksi text NOT NULL,
  PRIMARY KEY (id_setoran_buku, id_transaksi)
);

CREATE INDEX setoran_buku_pending_foto_nota_idx
  ON obos.setoran_buku_pending_foto (id_transaksi);

CREATE TABLE obos.stok_opname (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES obos.setoran_buku (id),
  tanggal date NOT NULL,
  id_barang text NOT NULL REFERENCES obos.barang (id_barang),
  nama_barang text NOT NULL,
  stok_awal numeric(14, 4) NOT NULL DEFAULT 0,
  qty_masuk numeric(14, 4) NOT NULL DEFAULT 0,
  qty_packed numeric(14, 4) NOT NULL DEFAULT 0,
  qty_batal numeric(14, 4) NOT NULL DEFAULT 0,
  qty_retur numeric(14, 4) NOT NULL DEFAULT 0,
  stok_hitung numeric(14, 4) GENERATED ALWAYS AS (
    stok_awal + qty_masuk - qty_packed + qty_batal + qty_retur
  ) STORED,
  stok_fisik numeric(14, 4),
  selisih numeric(14, 4) GENERATED ALWAYS AS (
    stok_fisik - (stok_awal + qty_masuk - qty_packed + qty_batal + qty_retur)
  ) STORED,
  dicek_stok_oleh text,
  putusan text,
  nilai_putusan integer,
  harga_beli_putusan integer,
  qty_selisih_putusan numeric(14, 4),
  kasbon_email text,
  kasbon_nama text,
  waktu_putusan timestamptz,
  CONSTRAINT stok_opname_nama_chk CHECK (btrim(nama_barang) <> ''),
  CONSTRAINT stok_opname_angka_chk CHECK (
    stok_awal >= 0
    AND qty_masuk >= 0
    AND qty_packed >= 0
    AND qty_batal >= 0
    AND qty_retur >= 0
    AND (stok_fisik IS NULL OR stok_fisik >= 0)
  ),
  CONSTRAINT stok_opname_putusan_chk CHECK (
    putusan IS NULL
    OR (
      putusan IN ('kasbon', 'beban', 'margin_plus')
      AND nilai_putusan IS NOT NULL
      AND nilai_putusan >= 0
      AND harga_beli_putusan IS NOT NULL
      AND harga_beli_putusan >= 0
      AND (
        putusan <> 'kasbon'
        OR (
          kasbon_email IS NOT NULL
          AND btrim(kasbon_email) <> ''
          AND kasbon_nama IS NOT NULL
          AND btrim(kasbon_nama) <> ''
        )
      )
    )
  ),
  CONSTRAINT stok_opname_sku_buku UNIQUE (id_setoran_buku, id_barang)
);

CREATE TABLE obos.kasbon (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL REFERENCES obos.users (email),
  nama text NOT NULL,
  nilai integer NOT NULL,
  id_setoran_buku bigint NOT NULL REFERENCES obos.setoran_buku (id),
  id_barang text NOT NULL,
  waktu timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT kasbon_nilai_chk CHECK (nilai > 0),
  CONSTRAINT kasbon_nama_chk CHECK (btrim(nama) <> '')
);

CREATE TABLE obos.kunjungan_sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES obos.pelanggan (id_pelanggan),
  rute text NOT NULL,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  jarak double precision NOT NULL DEFAULT 0,
  CONSTRAINT kunjungan_sales_rute_chk CHECK (btrim(rute) <> ''),
  CONSTRAINT kunjungan_sales_jarak_chk CHECK (jarak >= 0)
);

CREATE UNIQUE INDEX kunjungan_sales_toko_hari_uidx
  ON obos.kunjungan_sales (id_pelanggan, tanggal);

CREATE TABLE obos.kunjungan_pengirim (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pelanggan text NOT NULL REFERENCES obos.pelanggan (id_pelanggan),
  rute_pengirim text NOT NULL,
  rute_sales text NOT NULL,
  tanggal date NOT NULL,
  waktu_masuk timestamptz,
  waktu_keluar timestamptz,
  jarak double precision NOT NULL DEFAULT 0,
  CONSTRAINT kunjungan_pengirim_rute_chk CHECK (
    btrim(rute_pengirim) <> '' AND btrim(rute_sales) <> ''
  ),
  CONSTRAINT kunjungan_pengirim_jarak_chk CHECK (jarak >= 0)
);

CREATE UNIQUE INDEX kunjungan_pengirim_toko_hari_uidx
  ON obos.kunjungan_pengirim (rute_pengirim, id_pelanggan, tanggal);

CREATE TABLE obos.retur_toko (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES obos.setoran_buku (id),
  tanggal date NOT NULL,
  rute_pengirim text NOT NULL,
  id_pelanggan text NOT NULL,
  kode_barang text NOT NULL,
  nama_barang text NOT NULL DEFAULT '',
  qty integer NOT NULL,
  harga_jual integer NOT NULL DEFAULT 0,
  waktu_catat timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT retur_toko_qty_chk CHECK (qty > 0),
  CONSTRAINT retur_toko_harga_chk CHECK (harga_jual >= 0),
  CONSTRAINT retur_toko_rute_chk CHECK (btrim(rute_pengirim) <> '')
);

CREATE UNIQUE INDEX retur_toko_buku_uidx
  ON obos.retur_toko (id_setoran_buku, rute_pengirim, id_pelanggan, kode_barang);

CREATE TABLE obos.barang_masuk (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  id_supplier integer NOT NULL REFERENCES obos.supplier (id),
  id_barang text NOT NULL REFERENCES obos.barang (id_barang),
  qty numeric(14, 4) NOT NULL DEFAULT 0,
  nilai integer NOT NULL DEFAULT 0,
  id_setoran_buku bigint REFERENCES obos.setoran_buku (id),
  CONSTRAINT barang_masuk_qty_chk CHECK (qty > 0),
  CONSTRAINT barang_masuk_nilai_chk CHECK (nilai >= 0)
);

CREATE UNIQUE INDEX barang_masuk_buku_uidx
  ON obos.barang_masuk (id_setoran_buku, id_supplier, id_barang)
  WHERE id_setoran_buku IS NOT NULL;

CREATE TABLE obos.ongkir (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tanggal date NOT NULL,
  id_supplier integer NOT NULL REFERENCES obos.supplier (id),
  jumlah integer NOT NULL DEFAULT 0,
  id_setoran_buku bigint REFERENCES obos.setoran_buku (id),
  CONSTRAINT ongkir_jumlah_chk CHECK (jumlah >= 0)
);

CREATE TABLE obos.setoran_pengirim (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rute_pengirim text NOT NULL,
  id_setoran_buku bigint NOT NULL REFERENCES obos.setoran_buku (id),
  jumlah_transfer integer NOT NULL DEFAULT 0,
  jumlah_tunai integer NOT NULL DEFAULT 0,
  jumlah_bop integer NOT NULL DEFAULT 0,
  kasbon_supir integer NOT NULL DEFAULT 0,
  kasbon_kenek integer NOT NULL DEFAULT 0,
  waktu_setor timestamptz NOT NULL DEFAULT clock_timestamp(),
  dicatat_oleh text NOT NULL DEFAULT '',
  dicatat_rute text NOT NULL DEFAULT '',
  CONSTRAINT setoran_pengirim_rute_chk CHECK (btrim(rute_pengirim) <> ''),
  CONSTRAINT setoran_pengirim_uang_chk CHECK (
    jumlah_transfer >= 0
    AND jumlah_tunai >= 0
    AND jumlah_bop >= 0
    AND jumlah_bop <= 170000
    AND kasbon_supir >= 0
    AND kasbon_kenek >= 0
  )
);

CREATE UNIQUE INDEX setoran_pengirim_rute_buku_uidx
  ON obos.setoran_pengirim (rute_pengirim, id_setoran_buku);

CREATE TABLE obos.setoran_kartu_simpan (
  id_setoran_buku bigint PRIMARY KEY REFERENCES obos.setoran_buku (id),
  isi jsonb NOT NULL,
  waktu_simpan timestamptz NOT NULL DEFAULT clock_timestamp(),
  dicatat_oleh text
);

CREATE TABLE obos.mutasi_bank (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_setoran_buku bigint NOT NULL REFERENCES obos.setoran_buku (id),
  tanggal date NOT NULL,
  tanggal_mutasi date,
  rekening_alias text,
  jumlah integer NOT NULL DEFAULT 0,
  berita text,
  rute_pengirim text,
  status_cocok text NOT NULL DEFAULT 'tidak_cocok',
  nama_berkas text,
  dicatat_oleh text,
  waktu_unggah timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT mutasi_bank_status_chk
    CHECK (status_cocok IN ('cocok', 'manual', 'tidak_cocok')),
  CONSTRAINT mutasi_bank_jumlah_chk CHECK (jumlah >= 0)
);

CREATE INDEX mutasi_bank_buku_idx ON obos.mutasi_bank (id_setoran_buku);

-- Hanya postgres/service_role. App tetap public.
DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'users', 'lokasi_gudang', 'rute_peta', 'supplier', 'target_sales',
    'pelanggan', 'barang', 'supplier_harga', 'setoran_buku', 'absensi',
    'transaksi', 'transaksi_items', 'setoran_buku_pending_foto', 'stok_opname',
    'kasbon', 'kunjungan_sales', 'kunjungan_pengirim', 'retur_toko',
    'barang_masuk', 'ongkir', 'setoran_pengirim', 'setoran_kartu_simpan',
    'mutasi_bank'
  ]
  LOOP
    EXECUTE format('REVOKE ALL ON TABLE obos.%I FROM PUBLIC, anon, authenticated', t);
    EXECUTE format(
      'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE obos.%I TO postgres, service_role',
      t
    );
    EXECUTE format('ALTER TABLE obos.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE obos.%I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format(
      'CREATE POLICY obos_postgres ON obos.%I TO postgres, service_role USING (true) WITH CHECK (true)',
      t
    );
  END LOOP;
END;
$$;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA obos TO postgres, service_role;
REVOKE ALL ON FUNCTION obos.users_rapikan() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION obos.users_rapikan() TO postgres, service_role;
